---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ddns-updater
  namespace: ddns-updater
spec:
  interval: 15m
  chart:
    spec:
      chart: ddns-updater
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultCertificate: domain-0-wildcard
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 10227
    # yaml to json
    settings:
      - provider: cloudflare
        zone_identifier: "${DOMAIN_0_ZONE_IDENT}"
        domain: "${DOMAIN_0}"
        ttl: 600
        token: "${DOMAIN_0_CLOUDFLARE_TOKEN}"
        ip_version: ipv4
        ipv6_suffix: ""

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                CONFIG: "{{ toJson .Values.settings }}"
                SHOUTRRR_ADDRESSES: "${DDNS_UPDATER_SHOUTRRR_ADDRESSES}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod 
        hosts:
          - host: ddns.updater.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
