---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ms-sql
  namespace: ms-sql
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-sql"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    image:
      repository: mcr.microsoft.com/mssql/server
      pullPolicy: IfNotPresent
      tag: 2022-latest
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        privileged: true
        runAsGroup: 0
        runAsUser: 0
        PUID: 0
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MSSQL_IP}
        ports:
          main:
            port: 1433
            protocol: tcp
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: true
                readiness:
                  enabled: true
                startup:
                  enabled: true
              env:
                ACCEPT_EULA: "Y"
                MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ingress:
      main:
        enabled: false
        integrations:
          traefik:
            enabled: true
            middlewares:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: sql.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: "${MSSQL_LOCAL}"
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              enabled: true
              cacheCapacity: 10Gi

    # app-template (custom-app) has a built in
    # postgres db will not be needed.
    cnpg:
      main:
        enabled: false
