---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    defaultCertificate: domain-0-wildcard
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 10095
      torrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${QBIT_IP}
        ports:
          torrent:
            enabled: true
            # change this port only for torrenting
            port: 46881
            protocol: tcp
          torrentudp:
            enabled: true
            port: "{{ .Values.service.torrent.ports.torrent.port }}"
            protocol: udp
    ingress:
      main:
        enabled: true
        integrations:
          homepage:
            enabled: false
            group: "Media Downloads"
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: qbit.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
              cacheCapacity: 10Gi
              cleanupTempPVC: true
              cleanupCachePVC: true
            src:
              enabled: true
              cacheCapacity: 10Gi
              cleanupTempPVC: true
              cleanupCachePVC: true
      downloads:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${NVME_NFS}
        mountPath: "${NVME_LOCAL}"
