apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:MBTrAJw4RAfjnzsL6a2zMNLTZsiTarEMdqZTHG3K1EQ312dSuVfmTp6WeBvu9sAVk+NsA7VggbWvtipIe9/OggRYH9ZwpUl0KoEyUIdGAi2t15EjAg6CmXQJ8HM2ojR2qgPPzHgA+tGgvEE+sx6Iyo44ZnyG6UD5pP7glA==,iv:3HE0gPZbmAaT2Upj01DjGj6I3aJ/SGgWtuf1w6hw9Uc=,tag:snWfBNGK3MSBKJDEekuRnQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV1Nhem5qRW9sUTFmMUg5
            dmRiUmJyUGJrbTBmQlRLL21xb2M3TFp1RjJZCmxVWlNKNk9KWXFLU1pZVi9TakFt
            azR6aGgwNW13K1lTSGJzUGZoUm11RHcKLS0tIEtVQzBDRmE1QzlhU1hQRG1vT0Fr
            ejZDU0dYeFVUaE1KYVMvd0h5K2ttQ0EK8Ral+C8g087BhyH8An6oaqBiRFB2e+O5
            LOjwUIEYLRQxiIUZbUYPMDCvE5m2gpMVOobVdtnwfZRup3DOTsP0eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T09:22:13Z"
    mac: ENC[AES256_GCM,data:wRLm/ushUWMbUM8wnm5golF8WAZEbzzkPMh1RtV4kfD2z6G/ez24khkWAiSuWnItDlbJGKzruekjwnTbNiqGXAESol9vP3+UQHAt3lvUlPt87Ew8moIpSdajh9Xg/QGU+UImFpFktPIYFEwv80s5XXPhOTTTLAVQB+FgMY3Wvlk=,iv:nYikeeMd59S1MVypvGM+vLYL/iBCgh2CBNEWj7VnPxI=,tag:6buvb0pUY25N0HhsQDI/yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
