apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:mKu9WKWyc3OR6DTqvfGbJxOlOdPAfJkyLbwOTlCmeLRw7FJwIzzfRWtBwwwqpMyhCZ1rPnu+pwgd+EBvldD2zH6djjzNuCTA/5MEciQWu65LC/Ap2O6Qwz/GR+WPJjHvXxIwtnIThwV3s56RtI+LYNfCIx7RdM1TkupVNQ==,iv:WdujCMOe1zDQlviEW9dI7RAk1AMTBOUNmz7uGW4uyqY=,tag:JxB0Y9XCkUZCveINwld5uA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUE4yTkpRbmVET2p2TS9M
            b3QybEhjdEVMWFdad3VrY21LQjBEUmlLZGpZCmlpbEZ0UGk5QWpNVGZBNXpJRTJO
            ZDBVOG9iSm9ZcTVLUUZyNHhUd3VFdlEKLS0tIFRTc1crQktYRnJ5alhJaGlmYjdp
            OFZwUC9HRkVkL0pqWWZjVDhKQmdNT1UKhpJKU8oqvZB2U8XP2TcTKEM0dlwY4b94
            NQcP7Oj6WkwRdCP2DOJfzKL+bdiIoocK7s+plhEtJjXgTyprcJerpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T14:17:54Z"
    mac: ENC[AES256_GCM,data:tOeOtJRqOVhI98L6TWJXu2v87ro0riFctT3PxiscWLm2hIO0HbkmsC/BYUiB1vYrvVvKQa/xERslXH9EiGR1u6xndpeFguHgnu5BszK59IKENZrCPcKtyJUpQxIEcN1/G1GG8u6tH8xrkyYbc5pJ6RY00/jLn9C6nN++RNQNk3Y=,iv:84ubfheLw8cBSVssRA9Q7qbTKBldbN3kCeYz9q+4zVQ=,tag:PBzVtwf4UpPZZeHqxf3FgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
