apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:aJhT9haBKUGfjn0kZxtrnYaG5ZCU/7L1blpisP1dCaS01JVkJo6WeeuBHQi+VtQL2wlLue4zLVIvZSaL65ZcyYhPWrF2owoi2KlJQophz8P6HC5H+heDqf/nFNxGILKh6FV7M24iCeycLwUrrhOF16UUtR1bSEdvKgCBFw==,iv:lYjZfa2sDLVZDbNpFXBO1eIfEwUcoqlo1hhi9sH5wUI=,tag:rR4wQMebO/ouJtrbtthbnA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUVRKMExKRjVoVGpjeHpT
            ZzhtdW50MzdwODdvZWFSTGNMOGpLdkJqQVVNCmhqZ1piU1p2QVFRN0ZPdzQxODkz
            anhUUCtpQ0ZaQUxsN2lqSVRiR3ZiTmMKLS0tIDMxT1I5UVRNZFBnOWF0aHBDaGtC
            cEllZnE1T1d3R25aYlM2VlN4S1RjeHcKMBs2nPBU6BA7iLxVXKMcs+q3MBQlkQvo
            ZkNPZ7CbzehObDyS4kmzZX2lfG4Tvka85WwkZTWAQWmXfSQsNNYAxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T23:50:21Z"
    mac: ENC[AES256_GCM,data:9DwM5cUGl6i4e5qU2IMH+qwe6Kbfhmfx8o0YqPYRpQXVN/XplMl8nFRQy4VQmojooaS17i28InskKvEzVcMNUvZiDqZtXBnnaop1vVSlDDocyMYYUY4LNcUdlLhYREr0g8stUH3YbK+M7PwKTyf9MIphqSdrZjBsp/lG0VuWy5c=,iv:ZHGXKN3uurF/D34Cv9U9opzYE3nfGkTwNaaRF2i99ko=,tag:RAZPKvXbdqbCq0HuSRPN8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
