apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:OM5zn6bfxYSeQW3DjUqjxk/JRcbhzryBZ/kHW7JllEDZgjFKS2+67uD/9jPVdGMWtpqqlbS1/6JVUxKS/7NrfL57O34+H0WZC81JZxoiLMH1CyNS2jMY/t/S6J1Ba+t74++4uVES2hoVzboGHub6/W5QGldmtkygzicoYQ==,iv:VfV1oS6pWiK6mqr7+jBIW6UEMauQAB206zU5ygXeclk=,tag:ZltwZfPHY0ez16U4mjmGow==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ektMbzZ0TVNYZWhQNi9P
            YnZlTU9MNTJtaVJmalVuK1BacnNmMDIwODBvCkxuc3RyRFNxOW9CRmhtZmxCYlhn
            a2lFVUphdWV2dHl4a25vYnV5c1MxQ0UKLS0tIDFyMXh0QWdaNWFOQjc2ekwwV1Ay
            d1VMcTlNQ2J3SHRFdkFrUmtoaFF3ZmMKre7TQ4Lh0JHYNGZrz4mV6bFTZTrwyJna
            SdZJ0JfNCC/SHoYFkvaEjZHWdYNZ6byvyLl5gPp68qtbt/WTg8srCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T01:39:04Z"
    mac: ENC[AES256_GCM,data:rA98IVmAcxc7BCqJoERtjChfMbNF3d60gKAeG2NcHqw9x4Vi0Y4LhUtVs3y+g0WqDrv8djSLKys9G1yVLiSy4Qq8JJfKs8TYfwuXqzvIe9gX+FJxiPrVq84pK7tTnBdbTHWVDoO7EGdKBoccSMqEZ0IstzgwN3eYWOglpb2y56Q=,iv:p3ZtRnKAZONMHy9IF7id+9H837rO7zOMi7diOkunziI=,tag:1KkkwnAyz10l+Y0AUxFnNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
