apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:4ElBp0lFnzzsqo50bk/BIr1OaHohqlGfWoVMH6jO6AI8AnkJydjBLLl5Ub6py++xaYRHWVYHpVhKbIL98cCtSMNuDlWT+G3+z8ILvbufW/4pjGlZT92Y9isk/nCJfQ5joEc8e6YnlBcSH9oVu+7Q1+LvN3jXe2SpFuBgMA==,iv:r10nY1lIGnbhfLFjeDQ2R40PoWPry5izL3q7icN1l7w=,tag:SSXNHzF7z0WezzxjaXjNsw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUWlLcTcyYkhzZUxsOVRS
            WEszUFA3TldNV29FNVNqV2lDSVZ4MlVmVEVRCmZISUZBNGlJUnJ6T2lSK2wvM0lC
            SnRoTXVZc1hva1RwUDN2L0dGd1hTMXMKLS0tIHVCQTRIcGt6NUJIY2ZZZEJiVjNo
            eHZ6bkhYdStGcUtZTEdYc08rMytxVlkK8aGw1Ensra/BRdq6OLu46EhgqnHyUbUl
            ZeUw5sxqz7Tv3QJUGiiFwrbMgwdAxMVdivV4qnnk/DOGmo/gjH6i4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T21:51:45Z"
    mac: ENC[AES256_GCM,data:cQ8JPxftZ2qOgQFi5H1myD4gMXTsz534wxrCy4d9YWb7hyMuVo102jbcRqZzVx/fdEglpu6+NcrQcLVuRxDcXXmN6MkUyrGF3UyX/x3oChDXyIL25olCNlqQehtFzP/GOJtdfc4mLLnvCZ0MsmDp+EPXWIqTnEd2rvvpQD8Kh8c=,iv:/jhpuUb6Se7MxzekMq+wcJEcwMbUpfNWsUyTQCTq1hM=,tag:Si86fdU6JnBizN7m2w2t6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
