apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:s0OmqxHwOIN4BTI7xF+QWFA65mSfHLUFVktKps/VimzCrFJAvNmOfpiEU8GnaNskpmYE87fj2vJ+jwuAbSg18ma3lKJyiC4mar3YS4OSEUb8GV2tx9yT9xjM+irOhqWBBSNZ0XR0wLA4TV0ib6Cf1O8G41d1OiRYcrDFnw==,iv:jo8DuUy+EA4SV8NmifkwxWYDS2YzsrLZYO9NRkpV8qs=,tag:fYZ1ApidLAXC8xYggX5HzA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVzRtemkzc3EwU2U0VTY3
            NEtmVHZsZXROcGpiaUU4WWEyczdSSEZmbG1vCjZpRnBDYUZ2dHV2RFVYVzZRVWhC
            aVh3cEhZQ2oxcVFxZEhtSEFRWmxYbXMKLS0tIDFMcXgrU0ZzZThZVnZlWVpRVFNj
            Skx2REFHZFRaVkFVY1MxRkNsVW0vM00KUQaQRh4/vY4G312M9w0uHkrO4zxM6rbr
            e2s/e59qz6O3aqH+4ajRnlBoMnNjV7E1nmQEnf8UU2775sd7ldlP0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T08:39:27Z"
    mac: ENC[AES256_GCM,data:daSkesH46R8aPm39OQBTwLXtZpPsMiHt3rMSFZ3M1t2+584uzH/cNhjFCJX0O6bUbrYcgdMMMLnOiSP/n6bU9PZMPzJrwzmg4peTNSVeH/kaf5WQkuS91qyC+1QjNxzDM7HY8E6ve2LNG8ji+8C6z3fzoRJDy3jeCJHrcaXc1NI=,iv:4JX0OuxVRg/X1E9xSP5mcVeCDI0S5yKyl/Roa8q1eAI=,tag:iHLaB2s0QYkYCDTryINz5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
