apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:+WjCY/K1jKF5X7YphIDa0wKrogt8Lijvtl4SDmoHZKxW0+ORqynKW/S368jnjZ0AmIsssJS+bhEbAMn3eApW6/Q7rM1MaUb/Qz7JXx/L2MUDXy9O4pE0PirKEuVNCe/A/mBK8c1pqdiDgCtXaCbwVVh9erIFR+z573AzyA==,iv:LSdinHyhf+a5KBIqxXMzqGnfKRDZRD/NncTXdTQP6gQ=,tag:+3GKfWh7LKWXTcsI3HgmZg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OHFlZHM1ZENGRklucGh2
            MWdHYUVZdGNLczU2WGE2bjJIVUhsQWUwK2tzCnZaVTZVWmRoZXdlYzFIMUQzYkYz
            K29wNmk5SEVkd2kvNE9DSEgxaXkxSVEKLS0tIG42RXIxWWlUbHIzcHY5aHJVQ0I3
            YTcyMm9mTWx5ZzBzQXIzVXZRNzJiM28KhYTwacvW45whjAcj8X5AEdc5fO/fDMDO
            LW6x86kGQFeD1ZsVUhX1TtRlardU5kMStXEUBNGIL25iuACFcHKZ7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T07:22:37Z"
    mac: ENC[AES256_GCM,data:TbtfcfqmSa760F/a0L6xFiViBPymd5BrSs+23m4FQt+kUEnKp+HhHHJOg3bcXILxGxMkm0lDyRVonwoBuITMUgY1wKLxKZ2U6xRjrxqJLJBYoi9zPySEkYBOEX1RRUiJ2kCxqYf7wofo53ZR2fMi2CGw/88uLqUhNPtD5YFOklA=,iv:ZOJL+qgQkfRpXUmbkE9zbc9F8S4MDrWA8ry1oZ8O04M=,tag:z8+yDWhxsEvx55wwcfM8NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
