apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:F8Bf1w2VswrDXe7luzCmiHt6guER/Vsh3v4IC2ScoSsDvZyio3iuQqzsWiMxPYXi4TZ84FeMoy9WEIgSBVssBL+MmhQQc0SAkSo+NuOgjwy1AM12skj1eRIMDZIT704kBZfutV1/hKL0EbtaE7bp2Uv8l3pX2AlAy1OvJg==,iv:PY1mB9S+av84nWRR8yLFYrrEGLI4CkoqL+Y1F2qSlaw=,tag:OV05IuU0T9SDbekuZpToyw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGg5VEVKNGZTSkduQUpa
            b1NUaVRsUVpwM2E3T2xVcHR5OTFDY2RnZWdNClpMVGpscEpCRXFoVHJNcEgydjZR
            a1k0S3FRRkZkNkkyS0czUmhSN3VpMkkKLS0tIFR0aCtEQ0NjWDR2YkJtOVkwVmgz
            Vjk0ZDAvekdBRVRMYmt5V3BuUi9mMWMKzrjkc/8xQ1TT7qQC7OUZMcjaS7TaCIyy
            5DDR/ON9/1yrUm54MDmsz8u0HJT20+wqIyTyxx+qcgXmN/QMOYuHVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T07:24:03Z"
    mac: ENC[AES256_GCM,data:wnyn+EZ+Fw428Y75Q8GecdXJB6jYA+We7xQ5OtEU0ZSHjh/eNHvftNQA4BPXDy3uxERgHu7LEBQCl5yR5y0S3NfbmyxI1Z5ELyVNbKiRlQPSSf/bHUECqRKfi82vx0bRTUF5MPOfeuV8UZ2sx7Ce0jhlk09rXfJ7M5Cg0Rfqd60=,iv:3rBVaQF2nCMSMaTopOiUeC0XdeBKSh9T9gssWnTAPGQ=,tag:+RAoeouBOP3F8qr4gmYANw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
