apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:+zHvFEJId7yR4qXGMKXOK03a4X0tZCBLUwkIv/WV3ybCxHzUEMpHW7iZiHPV3wxkpVFQXtfqF48IoktxWp4jjNVMi4uLUPS0GzrShZr8r59XoJQjAVS0UcUQzoC9DAiv3Sxw33QyDpqLNxSYyLPvWBW0s0HYFLyut52/eQ==,iv:LmFj3h+wtaVA84yCqZPDQxX10OpUMobOCZhxl4kB2WA=,tag:g88D84JW1WF2fDhOVshnhA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOE5IdmgxenE0UktKM2Ja
            ZkFyd2d5Q3lsUVBYMXBjMG1iNGMrZmttT0R3CnFXcDhYalE3dExNbVU0aURGTEps
            Zm9STlJVSlRMbXRaMEJva2RxWXdWemsKLS0tIGRxdU0yLzU1dEdpcWgvdkNpa1Az
            L0lsRnI0NHgrWFE5VnM5MlZQV3FOWU0KDx9h+QT25RsBrfssbLiWKAPQt8QXp+Co
            fSJMsuecwJpV9s+qxXpvSr5TmsaSJnFF/WVvkfcqAOki16KsjWigcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T02:09:38Z"
    mac: ENC[AES256_GCM,data:H8X005k1Z2Ic1DVar26s3eOGM6L8Ct+n6sfhC7zysc3doyhDukMG0W22o+Yp6Vu+++SfjYaBfibcGCtBaANblAl4hYNE/oNvcGZyTwsf3lUVi9Dny+UJIQXavja8ec3+iScs3iQEhELhGHK75NHhoefEhULeE70yw3WxGrRaAA0=,iv:HpFl7JG3J2oKysOa1zOUNCdfczyACVIFXOo0hOUplXk=,tag:IgWusJQBhQ18hzG2aU9toA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
