apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:QDhAyDVyAU9wUKQDn1n3VNxvBvarcsRlsONktTxY1gP9DHVi5gZ1mOPd20mhP8NtMG3wEscUYjuRadLNuQRhx+vPPQFEjXxRv20mo6rUD1Jot56CgwyRpr9gZ3fHisnYCRYTPROiobzzKJPqqIVXHBZ0J6au0ojrwWhqUg==,iv:lTDJu1nsk8yvx3jkuyLz6KM9x0++co7nNd1JOooPEtc=,tag:Dx5rY8v/dJFydFrsHpOzpA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QWNvUkFwbGtkK1dNRFI3
            N2h6QnkweXg5c0hGS1lyeWpueFlXUnYwUEdrCkRITmtNV3ZCKzd4K1U0R3NEbExo
            T3R1TzRJOU5OOWQxUjhWdGRHVWxleFEKLS0tIDJzRXZqcEttR2VCUWR2U3JoTVFT
            ZDJvd2RQajg2R09QUExhbXRKUkI2eVEKibKy7amGnF9GfNo2b86PWuPuU587XG4N
            hM/H2WO8TiwYan1WZJ4IpLvpXW7YDAlslhrvXRR7S6FXBZy79aJCvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T20:20:18Z"
    mac: ENC[AES256_GCM,data:5QSsxXfphA/xwx3yUUZjzZthz9+GlXNWmI0fy1pj2tOr7SH2ZjP9BYQ5xbT9Lgaw2BUqJLcnRe2uHWY0ky0Ic6wAHEKX4msBx2u51TbyWtcSVhmeNJUCk76JJSKCyPV+SqzH6FnrA1WIN+UYSQz8sJmxoY7i4ARHmUhkrv43xSk=,iv:6olf0zotZM+fId32wO5cdq1amOs+SB+DaFb4dk7Rr40=,tag:is8lAjC1Zu1E5jDNOO44Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
