apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:QC3R04wN0ViXqlGCo4+BGioODNmJEESlY3R6F9lHXFqHgMi/5+u43+2x8vft9KmlUlCQqyAk5sFZAp4IBTJgOEaWdXz8pQmPSgUdIULTcbvJljpDyFOLdDPmNtgQo6kVfSD3DFfNt0scLu3HZMPjcesvFO20brnuQbfLUg==,iv:hXJKAOBpSwo7r/MDZqeoXFzQxAWN8BP3qLdRqrdoZxI=,tag:ZN6fk1Fs+UcYTVi/ULHJag==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdVM2RWs3U01RMm1OWGNN
            SkhJek52ZXYwMUo2TlBzNFJESjRTc2dhSVc0Ci9ha3B0K0FveDYxMUZSemNCWnlW
            RTJSdUhRc2duM0hDcUxjVUZHb1IyL2cKLS0tIEprYXFaU3JtVmJrN3JLY0l0NFk1
            UHZoSDJlOW04dk02cmt3ZFpMK2FKUEEKseRbmT+R3KdLfiZWt4/o6IRo6MDoHd3E
            iJKYLo3tVTUfZiZh742ZOtfAht7XjW+LM888HE74FARJNHEyGerPTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T04:14:20Z"
    mac: ENC[AES256_GCM,data:vgMJVGD9Nir8Bv9jjYFWbFbyalaVQOzzSNaxFgHZtEiN9jFVWySC2MUeO5RX4KtqjDp1beHqeOac9BIySllpYF9tC6HJELafw05YC5mO1REjB0ZxqbyuG63QCEqlepp9Ay+FUhOeMZdeRsyvjbeJk3Twt6fgNYNv67BwIqHp178=,iv:/cLLJbZXswaqEV3dADQ91SythFLJt75wxSxrHOzCFbI=,tag:URqfrh3vgpUGoDXte8AuuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
