apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:56TDluK0IUR7vyqrD13hD1LH7St2+2UDoJ6hkP6KkdEqoaddmzQa3iXKevOOWTTB6Tt1xkOfObQm7R6Ul5yf/JP54ErbkhhkuPrRTFBpxSUNuvJQbvJ/8wPXlv5oD42YtIeBpHmXPhWlP1xETyfSiw0x/YQJK6quU2tqvQ==,iv:F//YRldKx0EL+Vi6gFYAJKbxCoVTo7qX72tRWTps2Fk=,tag:lEOXeqdLANlrZoGccqxP+A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRnZKUDhjR0JJYTBhR09M
            dlZUM2h6QkxGKzZkMTVUTFoyVjN2ZUZHQjNRCjJtZGYwOVFFaVh4bFdwUTZYRkE1
            cVgxRi8xdEVsYXNDOXF0ZEpCZ21wMjAKLS0tIFdlTjhEQ1gyRmp2Mi9ibEphZmFs
            N0QxQXFycUkrdGJnSGxaYVFYeG13VW8Ktd9IAnA8j4wTKJz6X4jZZEaf9n3MtO2d
            s/ctZUqUgFNvXm0noiHhgYEMP9gWvPw1zopS6759UVmgFrkP7w/Fkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T07:54:21Z"
    mac: ENC[AES256_GCM,data:/jpVjEVGX4wvBk+zeGLXpo2R/g63Owxq1z9JVScRDJ88cxkWcRZAQ11/c+DSEygTD+n2oyjTTb+qHbN6YCgFBGi58C7b11AprMCZAw6S4yq3efdsGfwC7mFf3WUD7s+/WX0+JhGpmHS0yLhmW9ZDu3FjDgH11IZSYqYeS/17A78=,iv:Jtk8oiHgtRXaVrh5uk2rjZNufWON3ClP5xM6YMNTN20=,tag:O9gu3kPf2F2TYSSthrLo7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
