apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VN1rnVX45r7pWLxPRWG2s321lvShSJTN086dQ+dHD3d0/f3rACVRAWY3hnGeW5beWMFhPTZx3YDMSzEIaJ32Ogzsvh9jhaXKEs3+GuPCNHV7ph0QWF3jqE94siJQC+HL8x/Okqnm6U2sH40ZBrLWC/cyUiwhSzqVe0cWsQ==,iv:ciF0Ro8/VA5727DjuiVp6DsWjdJKvYO/zh4fFT3nrOY=,tag:jU1Ryl0zSHUY8OufKRSeXA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTzZXZlVDUGRYZHF3aThi
            VnpnWkhod3NDbVVFakhWRFJWcDJ3MW1UVjEwCnVzVGRQcS9Od3VtNlBzTWFieWlR
            K3Zlb2YydWtTRzQ1dWlmT2plYXhGb1kKLS0tIGFESjl1TEhLVUNRdWowYk4xMkdW
            bmlBRlA4YTJzU0h1c0hGeklhaXVPV0kK+7Q6bIaINGN5kTm8wffkMJZJ+LpWxeUU
            Ur9C8jadpARdb0eVannO3d7koHPkcf5cbOxJ2l9MxPht0z6STYU/9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T21:37:52Z"
    mac: ENC[AES256_GCM,data:gM4hzcxO0kbJrmAYVSkV+mf7N6TLXEAXW+c3WROo6OxGequD0o/FT00KwaufVFsEWug4To5Nr3TBU9FZfzGP3JuxJgPb1czlB6eASe1fG6w5tqdXfab9Jylp30O/4bWkb6A8/baBjESdoDHrNByaJDohB1afcFmYKxkaEgXraac=,iv:q3mlSgV0Vxj2YB9yA28BwhC6ta6qGPn92ikT/tsUzvI=,tag:tU4RUN//Dtgx178c5GNM0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
