apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:GFh1hZPhG+seIiNwv4tQANQECARNQAa9IN1q/1cBgBpnMxBXbnb6H65e8QeJrEIxPxpLDrsb1m7e4yJr7VBmYHMrHCjABHYbkkgCC5zhVps6n4VqMWl6kk91HMoKGKeKPvbGWPQDgNEh7lGMy0mftjoO1ImptnkuFOLuHA==,iv:O8YWqR2z17QbjK7E8C4mkSrdoVgYO4uIiEBD+tsJ2HE=,tag:SXaT9OUid/Q3FY34d76WNA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzczZmN1RYUUZKM1lXSlRp
            MytHbThnVkg1UXpRTW9GZnRRUWpQejRwR0ZZCmozNDA2U3NLRzlqb0ZEMTVjb0pJ
            ZEVwL0VBWGdrdDQyeUtlYnBHRHphTE0KLS0tIGk5dnRIUjBMK2JYeEcvTW82aWw3
            aGk4NHc0cC96ZmcyVW9qN1VQaEVxckkK9Vs7fvkoWvUuCUY/bNrwhTvvcsG/I2C9
            lKZMv1klGHd2fxEph5nmoQdy5CrxgCgByIXVVF2jcN/PzA5IPyjokw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T02:22:10Z"
    mac: ENC[AES256_GCM,data:u2j2utRNKv5XqgPfgt0oiW+HtlA9JJjXWhs9dZum51nqAmV8BczWSpBHEQNnXDQYYwJeaPOz+R4BiV6oHomBPwMAQ3jdisxNtMfpR5XELOikKKMx/SVuzSr3CRLIH3sXfpJHMdX4HfwCSeJbJY//reUCQo7UUGqO5TZkVEGPPpI=,iv:+o0L6Hj5oADoCwiZnHv3/n4EH00ruWLFtFgrDDM6HmQ=,tag:Ik3m+D3AlqxF0N4ov06VEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
