apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:d3I26g23plYplC42LZSIGbCANiCik8L4ncKjjVtcNpkYXvmKFG3mLxxKuRieblYimUnPG5kiyTa2v5yaZtspQxtxxu8Yao1nfjSsa/Ol8LOnUPxC/pmO6ACXn8giNNeMov7f9qRmCcHQo7dSDB0lhln35aUTnjSAak6e5A==,iv:zih1k3T/EJcXm/3qMtOTe1ob9dS97IBsZzt/g/fYXaI=,tag:lfuSzS7fi9kg0YcJQZ0F7w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUk12SDlwUkhNSHN5NXZp
            c1EwRmJYYzgybk10Vm9XcGVWMlRuekcwNVVRCnRITXpETXRWYTZNTHJxUjVJak0v
            cE1HaTBmSkhYMUhiNklTR1hCTzYyem8KLS0tIHY2QjhUK3FTNHk3bDVEYTFuNTdn
            djRIb1ZXMWdIR2hqa0R3cm9UOFdZTkkKphIuQ4+MGnz1ChmxYab73t6ngETEr5xj
            0ZByD3JKg7IfnTV715XnNxGLm+tGSqXKybf7bO5jDw0NfQfdukcDZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T08:17:26Z"
    mac: ENC[AES256_GCM,data:Jv0ifvEMUGFK37a4wPGZBZApaYFefPi2CMc2oOwvIdXZjs6JBbRRsR0s74m12Chn8pDnf/hq0DjQCOBtOnCfhsnugP8QPU5YFV+GM43pnSsZPuyHGzUYb+HmWprD3z64jZ751cjjEKL9B/EZ6HpH9ZmrWbhiDfQaFXFE6vEbzxU=,iv:tcfqPJ2b/yH9VoFuw3TjVqPKKzOrva59zruCzOyXWwQ=,tag:ix/wo7jWm5TzSPILi1lFAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
