apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:n1i11aKBVYexdrnZaPag8cETDdDObLx8UidmUf2H2Hd7y7Mq2M3MrNLWsKWRfnZTNqUCYLu/XnnLfxQeiFZhmg==,iv:Xs4eEqPdwHYpPKansqJXXILUFXaljV2QcLbqAQYPxfc=,tag:VYX8G4zlZQGsmN2PoIKVFw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEenp2SFVXVHBGUzBPK1Vk
            clFCeTdIb0pYMnovZk00K3NNR3grN0E1ZWpnCnB2c3U4ejBmYlZaQlJMMUhZMDNa
            czNiM09jTWI5bDFaeFU3dnA3K1lET0EKLS0tIDNndlRWN2JQc0Q3VlloR3JDU1d3
            cVB4TnJDbnBSQU9jQjV3cE1udkM5VlUK/xxPEJt4n87NTFl6UARy1+wu2CjiKddq
            NTv+8kGgnxP/EY4T+JABuuwpy7t7IycAlSvASEc/nkwwhD6LOMX/nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T09:05:55Z"
    mac: ENC[AES256_GCM,data:5KgdxAebyqWfc81iaJI0dqOVstrydIZ4DKNtQRitjVbaCcRbBD56YfkkAFtMOF/938nesm3ceAOFjGDdzvo3k6I8x6RVwMHRdtferXjBbAION9TccEaQvSS3hL/jyc1ZNp9ulNZaeXkReY2gYPURl3ueU3a1Yrdb5nc2PVDN8ns=,iv:E7sa06m9v6grw6UVw1mM8+0O6Ukm8KkR7X9FaJoWodY=,tag:uh1LQc8XFckBnZqt8VsdyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
