apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1q1LvqwjO01q1B6b9WwI0CehyaedSNgU87QO/TUFr5EQ0ZKvtx3/zLJ3hgr/QzjFHKXLm3IxWXYJycXxh4AnVA==,iv:G0gxTSCTYtHNTkFZtNtjAOleXUsSqkcOCyi4lYtTugM=,tag:JushVXmJCW50kQoIvjZ2EQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYmJPVE56Znk4R3JQZXRT
            M3YyOXIrZ0ZGVHM2WEdIbFpKM1ZNVE1JWjBzCjc5NktwY1BwTmlmc2NjUXpqS2Ur
            MXFKcmtRbmRRK0xrSFo4RzZ4eGtIeFkKLS0tIGRiZFFVM0VGVldxdEFnTUlneEVV
            UXNZMWUxcmJJdFUzVmx1Y1FCQWYyTzgKKob553YCy69uXDsXEfgC7ZhJ1nCHKkSv
            tkDMmcCG+7oLsZ51zIPBi3pXTfLHKOXGe3SF7B0Yqow5OH4kqcBShA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T06:47:19Z"
    mac: ENC[AES256_GCM,data:OpHLAIfbLYlga8N7TGbnvEhXl23gd4qtUCuhuWGgvj0f86sjEVVUSEvB1aj71JYgda2CZMSxw7D7lQLlxJLc/MswDqscO1YKmQWA2lDP+1bpFpYDItc9Jh8xvRKeE3521yCkjCLXv9Bdn+NN+NYFOFpqVCuD0qCksPYuZODwd4c=,iv:LidVY8esH49wTQdhkj6TK7IsjT19zd3xp6O5V8jYwdQ=,tag:nx2ccTx0SyNZoKe1MiXhTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
