apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:j/JYi3MPsDBqknp4yxeQn5lqCSVsBSlmffa6vN9pKNqxgi5OuV7V7iROEp4yNqduBzDloHJR3/8nGOnPQkHDug==,iv:OAiscaoGuZ4dvDFbbF4Zk/JnSTvJ3smYRx3nk4R01Zs=,tag:pirkVyLHs3ZIAV/zQwgI3g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeGFSUnhJZnp6QWpyWGZl
            MEZCcjlEaklNVkJsb3J5M3RpaUYzd2xoWTBZCmk3elQxNFladU1LeFJnQm9ycGFD
            YUZud1FKbmFUVklrQk14eXArOWJDcUEKLS0tIE9lUVRpQi94TzhmSTloVGV6dlE0
            UkhnaGlzZHljWDIvSkt5VGtwbjMyckUKJEsNvq4sh9Zxc2Pui7g8CgYN+foAGz3h
            hN1jtEYgA/+cfdtvqzm5jfggYfcZnHROFGOWggSIsTZuUwc3Pmv9iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T20:20:18Z"
    mac: ENC[AES256_GCM,data:U8IlxaqiJje/PJuugtxslZkUJo54XhUmIUXBUf2b216l0xKKT3D5KLFfAqPYJnsbNKAxUoLLHlNOg4oHzvlQL5DJSiAqrs3g/41ZOvibIYsIDt1F0MECoEEv02Kw5cC+9Xv7jF6c4Po0mFONg2HR3E/aORvsEkeLrglAtXD4XLE=,iv:7zN5LxrWcWuxjHsXR7zcRYpaFJp4Y9Ktq5DcqwDZ1ao=,tag:Kgg5SFoQAs4M6emVaHYBVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
