apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ttGl3vZlfwGBP0OuPU2qs25HDVdolvkUm5A+hLYwMWznfSPKrHHmH/cOyqcuBx5fI2Do7+xni6v6HdyK9QxK4w==,iv:iojp5VmZYxARKxLgJLgGffUCvracmcDmznPooiSJFd4=,tag:GFxRVf85PUOuKYKU+Q77bg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZFJvN1JPRVZDa0lyajRH
            RkEzQlRQMjVNb3FCeG1rZkEyVGN3TVNFbG13CmJLdUZBcTI0K3A1bmk0c1dFems0
            QXdyM2Fma3drOWI1T1ZwV3BhdytkV2cKLS0tIHE1OTNwQVE3OG02VkxOSFlQNWxF
            QlZhYkE5Zlg1ejhMSFh0Vzk3TEt1ck0KjtdXweUr64Ml64L8ufAcvmVYC0SbnZ8M
            yQGAIE2zZ1HrVc0tHEM6WvHyeyvlW11pkT/5L7GSRev1Rbo7iJ4fdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T08:57:30Z"
    mac: ENC[AES256_GCM,data:ipcIGQ3sFonTIY0sCytX9EgQxGpuenrVeRKmZYPqv6cQ7mhqFyCBWu7r0qBvRVW9T9rJ6wzKFftrnpg7KIdykG5NcUOwcalTKIiUW7RHe57obOftBvFGcOzuFIPGSYuqIW5Ds5KTtk9Bl0JDO3b9RDBnni7lc+GfbsiefSttlng=,iv:MjSc3IC9TfnJ7Y6AsARx21WXe/yGAz54L9/XkpOM7SY=,tag:BW+jdmONJYe1cMXck1h3SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
