apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WIWDnW3nBaqU/c7cPMhcDzRCQPqqZeJIznkMhh7O1sMmfQzxZaiCOcJP1T/e3Q90KwsTl9ao9OyItjlTlQKeQA==,iv:WfqUwMvU7shCohYFCWtAT/dqTMOcQRKMQ6howlPk/+0=,tag:3RfanlkW5P/4tUzZXQhdyA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NnVaUVVYU2VvZnlLYVVm
            M3UrckE1T3YrUkpxc0ZOQzc5U2U5cmMvTG5VCnlibWxjM2FLSUpLWlFoNGJBdXFR
            dWl6OGlyczA5Y0laSi93NTJNZHYwOFkKLS0tIHBQRlRKR1phZnlDNVo3NVZNNUVi
            YWVTdW5aKys2a0RSQVQwV2NEMmhLRmsKadZQP8356CZpiIp8MA8wCcoAcPMyiRlH
            hv46YcrrUiD3+nxRuip0qXtcwPi+xHDjrB1CI9GU4ob1aRTYw7RtjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T10:51:58Z"
    mac: ENC[AES256_GCM,data:tsXRubl1mmsSP6vtXpacsxIqU/G6HapmmlA1sw0k5EtJzHmVEqzMdr+HY7monI8fwkFvcyaVNJbqpD4dc2Q/UNdtTLtmaGnBaI8F+RDUgaHrmdn2ImNZdwSenFo722kTVmFLswPK9EYlvgdjiRHdrFT7sEdPwA+810y4+srWxTU=,iv:RUO8ES4bOHJwXf6Lh4iNq9de4r55d2hg2oeP2eQp+l8=,tag:eo3ZnYiIRymEhZzmhqm9pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
