apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RPtpfKqsnK3gb424vvjxmqFBJcFmwYk546Xemi9vfLgg+fPHmKUNZH9J87OMA07rV5qb59cBDtn1wIHT5j7JvQ==,iv:7wPXw31RvkhXIcGVqGTXT4zlkVB9V5Nsv7a01qFBqK0=,tag:0NRqQST8XyksZQu3tWOWAg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZVQzQ040eVNEelF5YVVC
            bjdEa1pVN3h2TG9ndjF4R3BJZEliQWs2OUZzCk5KNlRGZlp4b2FRV0lkNW5OdFhw
            MUxYdVQ0WGl6ejY3Z2VsZk50V3IzS3MKLS0tIEo2WkdoVGQ4WUtlc0ZPTi9CbWYr
            VzlRMFBJOVZiOVg1NGxVZnhUbkE1MUEKZz3XcWuhApy+eIdzdiu7RWMca3zNgCbO
            tAEYA9VKyurd+dA+WSXQlPHG1VHwbxp8z1lQKhj+Mv/27EsXiUbKcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T07:31:26Z"
    mac: ENC[AES256_GCM,data:eu99uKHdfwoQNvhpS5WUHId9+1Q3JZR9h7/C2Ao0JOquV0l47HosOdyBAcqUu7NaC6qSdhksdsiChjHRqeyQzQJeqv6XmAulKgXCUgKeDKcHm9CoxYJYLtjERgHJ8xpIHp8Xcg+vWcWT4sdG39g9F01dH+lqRbEcdE+HwcylgWQ=,iv:MIG5lcwXkpf+RiNh680tSTkC3CQlpcXxuy0d19K2i4w=,tag:3RFPt2NlI0TMVL+Z6Kh8Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
