apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ew8O9z+tGWlxyGhOhoAUDW8Y3o1K+Hbm+7fFlbFy7DqRLzhUdy7x6y1V5Nx1AUD7VIdWRASzL+xBvSKSMKzb/w==,iv:/Lu+L02XTy5KV2kD6p5f7EVewtBaK91oFY+AZcE+Jl0=,tag:tPjhVqW15UBVuF+JXjtGrg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQWlQa0xZd1A2WGR0RHlD
            SUZZWEZYOEN2VDlpZlVkZkNHQUxLQVBKSjE0CnYrVXIvK0hSV0JmZnAxaUFPbHVI
            UlpzaUlvVkVqcUUyQkRnZ0RPZ1FqRVEKLS0tIGcrU2tiaEIrWUdEeEkrSTZGcVE4
            ekdRekRZVHd1dWFXOEFXSlZRUnIzdzAKjh7IECMt9E/34FDTxauA/qcfgayi6Das
            Dt2qDoBH9YNZ6Lfq27ngzyeJmq/NKBbTMysctbgE5SIShS852AtQLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T23:35:59Z"
    mac: ENC[AES256_GCM,data:MV8p5UNYMY2vpGYorIHImeMazkO6OIEm/ly1qur9jCEqONXyKowNYwpXyvp37dXyJpfNv9Q1WsmLJUJiNjEk9Bdeuq1TbOrdOECmM5k0cfJ7dkLbKQbYD/1Fo07ucfCrEI8etA8txnWd3L844RCOe1wkxLjseW2gOFCu99ZKUeE=,iv:7HPiP85/ExWj80Nk+w1X7ZkPgZG+iR9trd/JoyE1UVA=,tag:DH5usv3RygMgXMhRIZFMrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
