apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:nNQkbzvbQ0BFJRUVWak5yH0TcW3V2YiVGDuuh6MC39WT/5vDWvLBMdI1CJSKe9p4gzPFl/LNLn5QOXJ7YlMFeIc=,iv:IGMSLvIrUFsNNMpJo/8xHs8geF52xaByxlWmq8II3DI=,tag:ZTShNKBv2naipxSpk5JOEQ==,type:comment]
    #ENC[AES256_GCM,data:r3ML5XyqiUG+T9Wvz9nH6MbXqclOPC9hwpGwDO5ClR+py7A+N10ERkJB2o0=,iv:h5fsLgsnIHTNyjwW38om9hWhWp+3/yVXlStMZFnulfY=,tag:Wp+NogiZGrrytGJY4FEQQA==,type:comment]
    VIP: ENC[AES256_GCM,data:E/VSQR/xqPiRiV7GCg==,iv:pMjLN+N3w+6+ncZOpIXgjRp8kfdgwWgTTNVXUef/wak=,tag:uOLdZk9Xsdxm5KH0bHRSdw==,type:str]
    #ENC[AES256_GCM,data:o1w1TCqDo4r28SS3+y+bqOloQx1BpxqzPgSd,iv:9b436JhFYyy/jWElLpa8G7PVfNmlx26d6TYOAtwRHNA=,tag:pP8x660JTmQ97GvWiP7ODA==,type:comment]
    #ENC[AES256_GCM,data:VzH84tM6vzj1dJEl3m8lYtrwZHeAWI5rvilo0FP/sipxgWOk6xBQFT7nMdg2K2aw36spuNkWHPnmZXBNWy6UAxVn6nva3KVL1nYMieZSk8V7ZkymThPeB5M=,iv:NtV4a92fPLnOtL0RWXtm265oeADybISeRmlMdU0mlZ8=,tag:aGQZgk7/0LQntJCuefkQ3w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hKTkaTdJiF6P7qXSww==,iv:zY9+tGI/27LSd1Q91Tt/sZ8T2QLWtC26GyoLGIog0Uo=,tag:Khj5jhTsjKBCnAfVDiiwMg==,type:str]
    #ENC[AES256_GCM,data:eF/+urQlPSe349glMAF1rIfBPMyjZ62EIbkvumB+2gboqQ==,iv:hE+A54QLEpYryZAsFoBn2b6QVdpA7f0/oaS1OOIZ9Q4=,tag:BBf09WhHGZyfaFaYH5K+Gw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:K8gxdH/y6wo5Tz0=,iv:40sjPqIJmnHzus2sE1SkNVX8GHpEx/faa3iK7oLFa7g=,tag:Y+T48+qwhtjCeTwt7mG2Yw==,type:str]
    #ENC[AES256_GCM,data:cMYNAgOeYUggVi4arEK/lyOCMCGjDnSDUlv+md+8DOxXuHpQ1ZyuU+YM19/9PU0=,iv:/9od5xGFzdC8rQ3ke/1oEpXmmd2JwKpYP8DcIWIl3Jc=,tag:h8iR3USEaxi27d2bzWK26Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:GZ7ORiC7RLhGDHO9+/2WvtEGf7AqjIVrV8L3,iv:r+yHFZ7CjDF5Y6iLqbsmSjLLlFAmNNHPZ/cc1w6Nnno=,tag:OFteFWOAdtYHl/mMNsCFcQ==,type:str]
    #ENC[AES256_GCM,data:VSbL6tpsKOYT29rVDj9mz9Pmh0IQXn57/uWXa11sVGO0Sqj5ROgKHnFLW6YGbTqQ2leF9B0/Men8M39lZWcaQ+02EDBUZPcPXuAyFcvNVjomrA==,iv:MNiRRqjH07SZpESFwpFPrGb8FUDatZHM7nGsiZrKNBw=,tag:60Ioa4ghFQ2DTRECJuLPYw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:1S+jL8xZBUB9T6SmHA==,iv:wwN5/1nfj0l7+8mlrhxkfOnZsvzUhdZA9GVBO3R6HHg=,tag:wDqgyDcO51EM2o4dyxBEWQ==,type:str]
    #ENC[AES256_GCM,data:tBGn57kKSC1DXoSmZVD1pOv1WGSAY6dFYaYwsjjbyfSL,iv:E/fsFpDVBIbGl3NSyGDdR1GPoa6foq4SSfUVMg8QKKw=,tag:NNYo8zoWdkYmUO9A0CCDKQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:O0OFUd+SPLfgtzv7cg==,iv:ll3DawMwuXQoVe0NyuKwJIBD+KR+/T+Gx7VLHYb3aH4=,tag:u3JUGULt05zKjBDYnEYYtw==,type:str]
    #ENC[AES256_GCM,data:BdQvyPkq9ZAHNg712oFKkCTxKd5RQ0S6o/Nj33bG/1fSvTk9OcW5FuerrsgSgL4nYn3awJOSezCIhzevFBN3pQp2QGUZrQBZtwABBZHG540=,iv:iVpubvtzIa/FYgR/e1loxjcjPTDaG3EsL2BqRQ5SLE8=,tag:oqxo+ycKOQGjkKnSQ9KQIg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:o5aNG5qBgGQBT+1tAA==,iv:x9UO0pl0E5NjON6ARg+F7RThuzenasSOKgkSolqvIcs=,tag:bMsnTEiPArNrbB9HkY5zsg==,type:str]
    #ENC[AES256_GCM,data:U+u4MSEVwrwRwSEeO9Rzq5FCmfSfENMbqxU+0BIrZlUMQ9SkAURXb8Qomozs3ww6We/y8vwxKENknBq9xbFVc9T77dZBkeE9ePuLuUo2MVXtCAi3J7f7,iv:DtPgaYptX/7WnseXGOriuG71oopLxK23PbpHUfqwUBc=,tag:F0mLnaeb975UN5fLJlLLlQ==,type:comment]
    #ENC[AES256_GCM,data:Y/PqP5mPZwlkO10cF4iwPWoU9PdxXuhJ8UXpt1Op9+VLZxu//iufMriiwIpX99082wvHxFyEqBobUnoB5STP59KgnVtv6nIVSShUn7R+4ySPGDNqQXwPYuYNKPF6m+pGwNGmPETClUUEgZCaOEUTEBAovz4dMYo1Q0Coug==,iv:yBhKCydRXmWKm4pGVoOhb6/yD6VC6CFySEoeZKK1ia4=,tag:PEp+O1wWM+m65LySp05AZQ==,type:comment]
    #ENC[AES256_GCM,data:7f0wUBM2eHHjYxnv7u5wvw8VdhGvVEAyMEuWJB+ICDRtgl1hyZaAUWWrkkjLS+UNW8sM5NXm/UhQfrdRolK4ckPau5L2YqFToJHgW8RQf5w=,iv:Rk6OWXYOh0DLgjvadEnvThEsnoMHpxZi1nMIBoesW2U=,tag:fgaX0nCLIq+GHWXYpLjgdg==,type:comment]
    #ENC[AES256_GCM,data:fkM11TVvTq10G5uyD9BCCnAAnqx+ILpim40bq1JpPmoy/ZKdkXjYgjrZi8qQ4Np5skoNd8Ns,iv:pywv0Ade7njT0a1KDAApgeiUxUQfv0KMcjzM5LAJ9Yc=,tag:Y92QLSQe3ioAx761F2PP4Q==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:y9UgldFo4WQvcy8=,iv:/vqWESBUrHoQxKWJtzF2lbtv7AFYgQher/ZTec6W7+M=,tag:saXgabAyMMQ2S6lXMNaIPg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:w9masNlh72E2mEYBN3co6h0=,iv:76uAC85EHnYqVtIgK4k7t5TXaORnt4FzaHx5esL+Ec4=,tag:d304/SM0h1T2NsI/jW++Fg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:866pJZiS88eSTCsQNYrKTHu9hsu7F2PxHK3JNlJxx7XnYX+sQbJh+g==,iv:8uwx5A+9YBUKlMx35PFSwtaDyefCD9vEFxzs/swjOEs=,tag:e7XaQab1VaxxwTATJ7xdWw==,type:str]
    #ENC[AES256_GCM,data:wSckc674fhDIp6QH1LoOeoWHX/ufvU6oLo82A3X7IAYVrURU88lZQRtx1VSKNQAzIY239jqpSIY=,iv:0yW4Vvt5mxuHOHIUM0oqelWZ0GPjw7sQG/0lNqHnx44=,tag:+LRx3iZ3lEVNRG66NbvpWA==,type:comment]
    #ENC[AES256_GCM,data:BX0VuEl9tEcbeXNwjyNYgDglONXCCZ/l7w==,iv:USDdhk61QFjADPqURQTqmHzR0VQyO4dIMnLACBFRRtw=,tag:F1KRHa8VY6mn5mu2H40uug==,type:comment]
    #ENC[AES256_GCM,data:ln8vmDl20QR6eCFLubPazyPioKFtWFXlBToQM8H8kpPyHiUuvpHJ5ORggzIk5m8RW2WO1+JmuF10RHOZC/QvAuzfM2u3UfhG/uQuVdg=,iv:OZDrWG4eXYq6kMij2sDS0P8jgafASqZ2KMfkzAtZxmE=,tag:y3hTDQWDjN5gAnguFU4N4Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:HHFMR9GUPz11rW4h3IxFTxumDuPzdV6NVNteuGYc5guqVCW3ZrOy8HYo,iv:rOKEctJg4r7nti1Y+G2CWenga1luDj4gaZY9iO3yvWs=,tag:+yotj3WllKg3bDUGT1O9Cw==,type:str]
    #ENC[AES256_GCM,data:45/B3LPepV/dgodTxYwqfyUCfL9FhM0WGp2bffkXGPjr++HZnqd8rFctf7mpX+mjXgQhRRaIU19+wqndevWojeNbN8PkCP0=,iv:atyXS2JANyRdCSnE4nwg7fsfn2Bg17wMZv/fxBvScco=,tag:uT6+A6IS56mnKgMzRbWCWA==,type:comment]
    #ENC[AES256_GCM,data:e3s5vjN7lgBDIzI9JDWH0wEzyCJIg6I/5aaZzLpsLnQ/wh9mSup2Rl0g4yaQFO2fgqhw2R3T,iv:THreQUJkA7DetZgKKADkBDAzDXHZyS7R0a4SeeZp2Ok=,tag:iaA1OFhfyy8aYqeYt/DIHw==,type:comment]
    #ENC[AES256_GCM,data:JnFtpqzk2w9hsZRb75N1bjA8ZSTViqDY7qwKlY0jF6XdB3Q=,iv:JeWOitraWpuF2XayxqK8ct4OJ9Q36cOXWVD/KpI+LSk=,tag:5JeHDEeCVy8G0EJsF+LLsg==,type:comment]
    #ENC[AES256_GCM,data:EJCGPO0Z2ZB9ZM3sy/SXpEdfeVKDP2WgTElhnlp4AT2GjTPO+dQe,iv:wiDeO6uTl7E0ZnhC5VCyKjgWZl2FrCDz9007a95mnoQ=,tag:t0UwMYGfhSJ4esa9LszLtA==,type:comment]
    #ENC[AES256_GCM,data:i/RO1IkAUWlgCaGytMg=,iv:UK0pBOiyNh3qKWuekNGZ7t5UjN8PLEEK8B6FpN3YKSk=,tag://xq485JGd+2hXnd3F1Msg==,type:comment]
    PODNET: ENC[AES256_GCM,data:pVMi8Q3jcw/KH1Zwbw==,iv:Effj0Ih5EZmrAY+isYyZx0JVT6a/vzNSFOWJT3Od3fU=,tag:PkQUaU8XkwGKYanA3hpwWg==,type:str]
    SVCNET: ENC[AES256_GCM,data:D9qFm1+zW1nbRPseag==,iv:ltei52Lvb80AxU1Uf9wijimxyyxFkUmV3VX3gIc7Cw8=,tag:VaoIehkgucAUTh8mbubt4A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:NZR9vQ==,iv:D9/WxrR4KeNfYT5wfxAVii64VOOukL3TGEHXshC5NMk=,tag:SMED7Mb46lTyNT8oHZxiTQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17yrg4567h6qxz80uvj0h3lxgdk4f0dfmd6kf7xzg5hswtlngsqjqe9fj3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Wk43N2xaOTc3ZnlpZFNP
            QlZHdm02ZzMzRnZtdkE5Mk9iSmgycy9FMWpnCnFPT1FsdmhwRmtzYWMzU202RDJO
            RURaSmtlSXpSZ1JTTklDU1Jtc1FZdVEKLS0tIGFaWjdBZUZteXo4YVZxMU9LdTJJ
            MTdSWW1EMHJlcmZRQlZUL3hEVzBmdG8KDmFUWBJ8uBty4QG5RS606qiUu7wjgzWZ
            vxG4z5q8ezVz7Ro3DPmZeh6pAUC8li4vGigF+JP4pH37FseMt6yt3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T09:11:45Z"
    mac: ENC[AES256_GCM,data:huv0gHXASeXLG4SmmP+QkwqLmSp6ljo6S/7wGkp0HSJDhLJ+7E1d6UdwAxjliD0GBirKSp4OVNDi6syJBg5voQyBoxbGiEF8mKSsbmsvAb1/+aNJ2ezlN8+x87xwsXfxobhaPbz2x6CX8xjkSYxFGzc1MYbnOccxIl8H+2OzOcU=,iv:pdFZzLbKE4FpQtatP2+FcvEQmei09Huvwa3Khtp7gc8=,tag:wWjeDaSy+vzJ6oGSh6UchA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
