apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:RkjkWy3N5Ce+NvG5BJMzG0RLgM7E1qxLLNifqHtSZXfYHy/9kYIByZMk4zzBM4CEkw8zIPvEkZxOLcKDQjgU8bg=,iv:6Zb2g2wygR2EhepsMVdsemFkrv8ffgD1986g3AT6RqY=,tag:e5aPGuSQ4LlYwuA4z3Hg6w==,type:comment]
    #ENC[AES256_GCM,data:sOKHbp8L/iq4DGkueiVXYJA+WJPHWoeMlCvr+gM+EhXGimy2wknjHtAy4rI=,iv:4enhmL64wmmDhDQBKdEeRQWix4Cn4s0eaETHu8BEbWs=,tag:bQkNFAMin3pk8EF6gokK+w==,type:comment]
    VIP: ENC[AES256_GCM,data:7uPAHyYl7qFV3JFgaA==,iv:P965QUu6ZRTnemHKca/roR722ECWhp58lvZBxnTbP1E=,tag:zAbUiVKk5tWLx5jSdeAPDA==,type:str]
    #ENC[AES256_GCM,data:uBFT94iWqvrrECdF2HxN7lOnHebcnFs3yqaQ,iv:Wek+g49xXnvhVly1qTWbEvwufKqkmqekD/rPPjtsrHI=,tag:OCap8L//OrVg/uFV2Bkjlw==,type:comment]
    #ENC[AES256_GCM,data:Cjzwn99ErTCaqH6oc2fAO39qYlpqTFfD9hTiwzAfSWpYLlFP1a5ASUJIdvg3pDD3idQ7Cr9nb3uQuJjhxAhVij4dqi5nbh7Eum019hgEvBKD5IgL07y2mX8=,iv:gi/DD1r//P+ipxNt3o63qumfScWGGDQMSAqv7tAFQy0=,tag:RQOIQAUzSBMVGlv5HWHnuw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:LF7ra/pkbvd3n7rF0A==,iv:Kk9M/tw/DklAn/00Og0/E68HQWb7q1d5q0+JtI4Do4Y=,tag:JKjF82s4mAd17nq3H/2+ig==,type:str]
    #ENC[AES256_GCM,data:KioPA+2VZ88zBLCYU/oz4pRlWZRDehVKQrLE/PRk1Gi50Q==,iv:3Zb+ZN+2xi4+kMIcXbsgiwxj0VfQPQOM5x7ubNsHkOA=,tag:5PuJrI8KgfftRFQeZl9zkQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:AoldbXpWmcqbBw4=,iv:lBz1YjdibvEYBprOeOk3C0nnD/xK47HfkJ6Fo+aiU7A=,tag:Yt2WKOZgUFRBpw7u83qbeg==,type:str]
    #ENC[AES256_GCM,data:6xYGXJe1znzAwG27TiBfcjopGcq9f5xVRWbAULcR8Wv74nVMbHUxBW6fbELhLW8=,iv:66g6JaL01NN+AdKqO1L8u0voLEqcBDmdkKYpgY2ctmQ=,tag:N5JhlAWz929nm7Mz/e+zOQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:P9Qje7SdLBW89rBTHPXyqfMCsDvnndgXjjAX,iv:eY2EJ7+ggcqa1tOh+CPMCBP1G+3hVr2zqAxVX+WO5Oo=,tag:BLlehKcJQ4CAODzcyiAA+w==,type:str]
    #ENC[AES256_GCM,data:ik5BlFjhWisVID2XauHonfteqVFTExiIXFbJZz7gbjlSthYNWl8SBwp9Dy2wf0hEoXfJ+fQqNyWbDvT6+AM/NNz/cV8P/pZ9cKvuajECExloOw==,iv:1lyqzlMO1u2TeKWpPqfIMoCDU85P0wqVab5d50uJrHg=,tag:J3BqTKmSh5lt6mmfqISsFQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:qqD+/CtTzJy7yCL1WQ==,iv:r8CLIHPr6H1zwVIoLi2iJ2pCMTxXmZuZAfd8coRknUo=,tag:NmxjOqFkMq7PeFShmFoEfQ==,type:str]
    #ENC[AES256_GCM,data:/No8qyBv0g8OB+0Wmt89OuBsubbRYGpQ+fuEQ8YSat43,iv:fHvaKRuF40vVJ8QisCAXUZrOjqEJQLa4gqw0iUHK494=,tag:KL0Hf9rn6KGKaXEVDoGElA==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:CZjTKsDFtIqLoFQqZw==,iv:O1mP+B8P2S++fikBNr6rc+imHJqC0gBnjauv0+L15xU=,tag:pVe9OVzPNMoViWds3y5trw==,type:str]
    #ENC[AES256_GCM,data:XWbKUVi40UtYZZiQ2UiSA8fUhrRfZYfR10Qxrn2vYXfgkrojWHXM3CRKl5xRDMrama02h5nCE5poVzZifrYungGhRfb4Qtd6GQ1Su8iFg/4=,iv:1q21MWIZJoIcwYpkYsYD0eoiT218qeNS0OL4p+FCEV4=,tag:g8ziXfuShefS4rHmbR9Iwg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:KVhNLzWXb2oQa4eiyQ==,iv:xmG8YSSUPgrnPeGEUaa0IOXzgtkHpXnH7EVi0vHhG5w=,tag:D3UNk3C4gCAUmvjHngghEw==,type:str]
    #ENC[AES256_GCM,data:2x5W969KHihm1cQ/n7ahW785XPNFqnctDVaIUf69iPOmvU+K5DG4BCG5KGaRR5JD/OIuaLNIPp4pCu+G7GVxyv61ep9t4ikJtnlTy7u8rhULZb45eBcr,iv:u5jTEjcbqLw/StlheJzZcec/zxVNnTJW24//JJFHQMY=,tag:ldYTZBvyPw09rq9tBKDrPw==,type:comment]
    #ENC[AES256_GCM,data:bf4zNMEemo6DidNfCWWX17kgQHcy1iAvstvcBubLRqRGpDis1aR1cAah/YTyuzYVtZgIySVH0UFzx/+Dk+OEvZE4yxAdkEINSKEkHm1ltT3smHpqlWxQ64iXe5r/pZzdplfUXlLpGpRjdzvaBuIjy+GJWeGW/lfhBzRxxg==,iv:rePBq1Pz1QRjhnXvkSFmEjOl0MSJOFyix0OzE5aq0tI=,tag:seW3YUKXAgo1bn/Hb0lA+w==,type:comment]
    #ENC[AES256_GCM,data:OtARV+E9RhNZMWWqOCyrMIAknwrnoXKSLS2ADFvn4AY3m5yTmtjtgycr/o5Yf5poQUTOspq8q1FwPjU3FUdcSOJ+5ZWNcbfGblaphvYDL2E=,iv:zrHu4+KY68XVA678jmEdVhgxRMmRUR5Cisa6PHELR1s=,tag:RhkKvUiTtJLKXV84fhrvDw==,type:comment]
    #ENC[AES256_GCM,data:rT/IFEnDAukgYQMKYRCBW+pGy3s5u/ctB5k5TjOnF0OysIk9zEYBnpar3BVq2228KrVJB0TR,iv:x2sMf0dZE2ryRboCFn6LgOCNeORsQg1ZIPI5a/9ZxtE=,tag:B6k+1WN/yg5qhNBO0HltXg==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:Bf/GF3Kui85dGKI=,iv:mhPnBZQ6067czAa3Om6rvaZBJAYnYbg+uweqNB2Ndmc=,tag:uCUwT/q88yZGJ58MPvt7aQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:vXU/CcQJS8bIhQMrzJyzVdc=,iv:9vNkpU6LQTqKbMByDjDlhQtDX6mIqnUwgwOTULC95iU=,tag:2QLb36OPR5I9iOMuVJFNCw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:0rbIiif40+T+Gpql1PUhoyJWcn78eiMXUDa4kjOp1V3TJ5gx8FE87g==,iv:IMdeaVN+1cu5op5IakKheNxIOKJDhos2u9de8mFPEF8=,tag:X5fivsZZx1hWtEOTOblXxQ==,type:str]
    #ENC[AES256_GCM,data:gjvnK64vJ3Q4b3mm5TsX6sH6DOG8GACIiBtIQTD6tkRSOJ9ZhkdyCi68I6Z4DnU4QaMfzSiGV1A=,iv:ONNlg0IX4xzved1a93K8sdl0vRiIU6DuupXJdTvIG3c=,tag:O4XukscrLKDVi7grC65s/Q==,type:comment]
    #ENC[AES256_GCM,data:y+RwHW/pY+P0Do5ORYQ2E2Db/WP+j+60YA==,iv:a501wvhHgy0mFVBFpYTN6IKbQfasxEWUvwpWGyAx6Sw=,tag:mrki2TYcRyPaVjWWEnvZaQ==,type:comment]
    #ENC[AES256_GCM,data:4vJiSMXGTa0kBYvH6zS0Q32bPgFU0yRXCQuMyBAriBbnjGyeow5c/Lc2pod3Z7vWo6uB4TG/u1ciC9YfsaTnBPD1TvHM8X4aQpqA1wc=,iv:xBxTa9sEVSdgUV7uuros2NpzYdT84bj1b4r5pbfy9j0=,tag:P/feqQYibp++lw0n5MPIFw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:w4C7aY8yYvm/bheUb2DPhmPWBwxUsVCDm0QxgDorDJYltuwr9aHU213e,iv:Kh0NRLT/KbNgGmutB+k4qAUTzRTeEtRRk/UXx1ae1io=,tag:om25QSAOrfNMJfPxzW3rcw==,type:str]
    #ENC[AES256_GCM,data:speS7wds0A47yWx+PKzaXIRWeo0fM/tL1Vgg/b6rctmRivGE3m4p/VY8RH7K83cSk/3feuAATVvs0lcoEPYBoC7fFLUwPFI=,iv:VG5FWCpkFB2lCBKAsD3bxvr4yF7bBwfr0tXyunUYrMc=,tag:gINBzmIlfBwycCsKL8MvrQ==,type:comment]
    #ENC[AES256_GCM,data:4j2KusEUfq9qGFBho6FgqUklvbgmb55L5QDLe53eKzvIhT+Qswmu8gLol4behXl4kKVkTBU0,iv:60gAkZXKiMcmgOpK0rAatctf1TrF8SHKdHqcFSIW15U=,tag:PegNITvDauaQtcgPTaIjLw==,type:comment]
    #ENC[AES256_GCM,data:eXR8y6DYcIljip4SIj5u77dFmKjwKO5L42K6NvlLKQHgL4M=,iv:yAD1yKaCYu5XlcImFHkCaKa4ohUuIHlcFaob9KLbO6c=,tag:V1L/RfG7BD6/yuZ21G9YPA==,type:comment]
    #ENC[AES256_GCM,data:hKa9xphMcKh6f9wriGLbLTaA/WvsKOdqam4jg2NBXifge5O3somC,iv:RRudxoAjtqVUxJnIhgOr3DQfB9MtEpWUTT8GXkzQ5A0=,tag:It13uNQAYAVa9bOBvBxs+g==,type:comment]
    #ENC[AES256_GCM,data:4Jp5K2fbtDW/OfM21Co=,iv:fD/BjVG1ymkECgkfR6QDcb9Nan1X8SAj7GjmohZsRog=,tag:NLMzmT5uSicvx9KTQHLgYw==,type:comment]
    PODNET: ENC[AES256_GCM,data:twscqKLDMn5wuuVbZg==,iv:FVk3YQXLchsVTgelV3EYTu/rDLyIiVrxIxxgAbE65Fs=,tag:HC6pNr635pVdsFt4TmVz0g==,type:str]
    SVCNET: ENC[AES256_GCM,data:4De9VJuTlnbs322wpQ==,iv:ckIQAtM4cXUnyK88qxhF7gSzCAMMCXmOaU9nGPdO67w=,tag:Ja9AzNuCuTD3soa4p0XtMg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:HmUZrw==,iv:QoviLKCEIyOTwZ6uWyg+T3Z/igPa3SP/IZEs0Cat60s=,tag:lwCY2PyTgPk2aTd1uHkXEQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17yrg4567h6qxz80uvj0h3lxgdk4f0dfmd6kf7xzg5hswtlngsqjqe9fj3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYVZlR05oNmJTMk1adlFa
            Z0NtbHBZQnorcW1yVWN4UTRya0ZOSTVVQm1JCjBXVjE2M29mdGdDUXlXZXZ2bUVk
            R2M3ZlBZR3h6M1IyMHRXT21scmI4WUkKLS0tIDFkRDlLQ1VWRDlSeDdRQ3Bybmo3
            TFgwdVNieUk3RFZ2RWhjOUg2Z2cvSXMKcKLGJtnhpyRby+fKz0wuzetTLcsF2979
            ehPbUnJv3ngr3LwrWogK7VLKXK50miqnwh1CiVywUjTQpmvSJxI3CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T04:55:25Z"
    mac: ENC[AES256_GCM,data:h+37x4QzDDqako5agLyJzwH0+KsnpAijra+JHu3lu0D9vQUHGSV87Hc/cb9VeMruXmXIatXMi9wE8RVbyrAX/g4ClJp90WuKeHuweuTaAtRt7iAup7DH0XDtF5Lw2Z/lC4B1wLnNfRoI7fdszR7xHW7WxnzsJ/l/lHqu8+rODP0=,iv:/ZVXxlp2ANk/cEFoNPzzXgbJ8DR8PhTg42W37cYgwIA=,tag:6534Vm4JFyMUNqSJ7POvTA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
