apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aCjqtDhjcqmmcXeVuGvB8bK1dTt201nTSQG2lOYj3O/t3I6wra6MR1CZVWeOfXlIaJIKuCuK5JXqAHdcuQZu7y1nyZRmEdOQngjQTuitDO7a0JvJgTVbaWDXf47xBV+QBdw7Xl0Kt7ezV7dTXeZJcQuVyKezxIHS3RClUFUsbdoY1exbwecg1PoYeMgQpBU369UbG+tZTxDNLBRCbDGdMknY1fiO9jdzkmhFr6LeuZGuIPSI8GeGdKUQTRRl0T+JoqPrKe22FGCibhJySzgwlifgz9NHrj+QCVXxamLAhcp0zH72UubY75D0fG6RfetCnSHyQhPzN5TeeLWb5WOivPlAETehWyWl3t5KEFwoRB1Oih7HaYplV8r0SNrv5eyX,iv:+ERz+PytTjTxDW8YsqSlWDl6OUXfndMOJyLUENlzqMs=,tag:sTPi8djqqVitQk695/WKHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tRRHBkBVNWCdEQn/YGxPKhD+nSs2/BsSUJfTblcPf4tjQeuIUaZmtVKnL95ENZfOwDx6raMdaJ4Gz8SshY3r6H8/UpqdYP3RhF9hD2r/qMpyvg8QWIfuRdPWXUxMktOoW3BEITw3VmsXUKr4Pzv803cLyc+Ue6zdAsvB7dsS5nlhvjZQebG/7srvdsHMF1+Co9nDkdDLnM59wae4yRWU5d2lcHNOu9uxoPU/Phqu0/kthpkMqBMZFwkoX9u57ISRGwNR7DFwWbRDWXdJhw==,iv:Cxp7AjNP4urjo9AVoZjjkykVdg4HMmDqWfNNJxnCkAg=,tag:91UoijBDRc/lLq0HcEElrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:iuGYDAZ8N6qPdz1L7S4dtspbC0cwBrc7EuuWim2bB3nX+RH1YvkzkkHMoeOckd+DXaD2M80Y+iLjaIYzVZ6InNCY2NSHqy+oK5RrRcfzxi/KcBsLWeLFd4gNKWVopScdZQbuVrnYRRBZnX+BndVS7WWY39bR63azt9KlLnZl4Jyi30mXuz/YvDKc0Id6JOKGcyhbw9pilNwGTC5Li4LQ8Bm6l2bCRZmzfIcq,iv:tt3Rt0Fl1+KRf8RgiircOIUvt/PNaBgWq0aeeZc/y38=,tag:DRdKfBNQy4B3fQxBHj63wg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObU82ZzhhNW9QKzVlTzhO
            QlRVVlZRRTBJWGtBUlRlSzZsbllYeEo2aEJ3CnVod29BYWJDbittS1FmZVNvK0J1
            SXFIQmdXUE1oc25EbktXd3BoWERyR2sKLS0tIHVLVWJVNWRxczAxL0VDSTU1YjdW
            OXNYb0tSY0swdGc1VE1PODlOVFFsVTgKl/XjuiH+aBUoXbnSfPWzJN3Wxow94qgt
            mMpNnjRfmzCj7jPLzUcEww3ucqn0UdPVpnWdXr8B0e8SxVchrRtopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T06:37:01Z"
    mac: ENC[AES256_GCM,data:so9YD6OQ92Hq+zg8FKk5HoyewKxzUk/qzyHqxAALGNouoB9MtG9kzettQ/UyWLKyrOYX6NkhYBtndagwkjYU09IYcTuiSyEWsKO+OA0piThB1KhtaMB+thUF/7AbAP4p5sUQfPOmvvVaqN87mU4UuffXL6ChKcsI24Dz89tXdyE=,iv:/2Nd4IADbVqxU0Pnflkryor0kqE22oPZHqwuPHGrpuw=,tag:nS2xfJ3EaMG6ZvfRc4/cQA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
