apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ktXCxgYtZR9HoyXmRFVVMi6e9Wx62wl/QJTWQSOeG7v1+OW8/SUg7crm/bUsmX7aczfKp+VKuH0Kx9S8TNbWO9yXV1FNAVOF/3OWAmd65We8+mRPfz/nTN5LoqrwZuD/KlewXeWoO7El3g6Lduj+3NubMoXtVShKv5H2h6o4QyOCnARh5OC+hh+HwIFqkmX4DCchw0YpHpO15r4q+3MIibvcOhtY3Srw3DgaYk4z5tkFZ+7I+yuVw5hgBEuBWhLZfkeEBInEafeDZD9fMapbLehwPYqxt/lyAhI/z7odNTxa2oYEBhdoP4EEOaL5vh5njRvtyx99LZhngyKr6INcWfi+6UfhTtJANW3vEwpON0NEZYOxG0L4Vqblrkqb1C6b,iv:ExPwx7hPG1QFNYXixEVLa0oe7RLHUI+PIvunMwf+crM=,tag:J47QzaBnTRf4zCXCZWN1IQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JKmkf3anbpm1VpxYcWvvNo7jymZqPM8voNYRtzLvG5yb17/j9vpT2JJ5r02PKkIwnDs3r2IrjEkWZN3Kp4YBXPYWOmJSwsI378S16dWKKDBq0+HK9DyONyh7QSr4eqfVrjuq4RbBG00ZIHjjao14V3TGuUA0oz92ZkSKdBhvFDVs/Lcma/Js0exxGWtSMo1hUE2BoEMKvM5KztvUbn6vvQM6JfQPO0ny27gOUOSxntGV/Y8WEaKAlnrLulFHyHhMiNWkFRUUq9+e59coxQ==,iv:g5/wjDwi3/yfSMkAm4jFJlYwx+DT/42dyMB4gsbxBc0=,tag:6pDgDa0WrzKWq9ciN2nIMA==,type:str]
    known_hosts: ENC[AES256_GCM,data:IAOOHsybbJ1Y9BSuhIhoC/Efre6QUjer0H8UVqmUIssLSbwlUQJPDSbDkwgoB691BJNuKtooFcl6N5+GujIWzm6s7oPubWOMlQsvbW37QJAczHroGEWB8HvaDOD7lq89vw27Q7yIfmWTE2ETElmd8hP24ZcKC5m5vTUMmrSNCOYV2naKW80W151QNdG1SEbjx9Y7yI4Qg+trq1+dttn0EJnnDDBNmS59smpB,iv:FS6khd0uP6hgRsyHTms37N4fyqS8rsZyKjAfIMFxiVM=,tag:mPkwdMbQ9KSZp/M/1IN0VA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVRpLzl6cXVsY2pPMTZ4
            Rkd6aG5TVHZnMVpVU21vZm8vYjUwRHA2djNRCllYc05KQTc5TExGdzhZNUt5SndS
            TmZ2NlpMWDNpeis1aUJLd0k3cHlWUHMKLS0tIHplelNHK2dUT2ZGU1kyRFAxSXJF
            OG1RSnN5a0NKd09wNzZVOEJBR2NZbFUK41+9zxiviygjgEm4zI6OJDBSjkLiAIAR
            6cMmOhgq6mevkv06NBK/vX6LrMgbH0JnpyVCp0NDBgD52zry94VutQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T07:40:44Z"
    mac: ENC[AES256_GCM,data:m3kP5Tnc9Lf+KM/DvdS8ctiU5ymrV8Krz1qOYEVj1oPsfqdW10JnDAqp8am/Fe6MOmi7h/vq2cnyyrkaGrfdhRXXPuyKzPHFxn+sNW1wZ7YaZiWJ0DZvt8OwOZWY/s87MJv5j/a1/gdpQh4FOCFdsfV9wXYlxU4+1HzBraAiDn8=,iv:mPOP6OMh8s3cNnpN11TfDALMk3DvD0gETc1PLyWptqc=,tag:8mvYknxZuvBhfE6qQ/R+xw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
