apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WadU9kJIm6tzqKjHW/FyRxcOC5oj2qHNVtF0h8vcUOTFGmCgy8CcSebqRvGeNk9zRUIkwMqQXC5uud6XnuJVBmyI+EWuZbr6cpfWskmZBj1RdnpSqyJGiGMa1aDusESbvZTA/rLnkHvf6T6N4sLy2xG9cw0/fEMCT78aXZY8SoQX5Rw2i0fq4lZobEea/ssDluAeJ/gH9T5//iXK+f8y7jaIOxfxFgSfwpmWjtvX6iYNM+NdDiNP8+ezeAlBA0tnZ/m6/HnjmTAJyODtmXzucwmt14VzyGBglkJHWpdtleXQUZ5DgnHEY5/b+NNsfXzbNFEQ3MSIhTmSSEr324ypmpC7fnoNH346qVkdK5Ru3WHdr1e0RzZMU8FPjxvfcO2q,iv:xXm5NEpmX0yJ9PsJhJUFAjWAzloQlY9w9yIGIuBmywM=,tag:RJASEWq1z4es59uV3L/leg==,type:str]
    identity.pub: ENC[AES256_GCM,data:aNmBDe3lLJUqXliP4mbihBxxUlVAIUjfyUU2bhIafWxfufUTF++peXnyqU+Omn+eMYItJ6mBH6RH9GhdoW5pnrd+91yB77fgfdaYwQ+ybAklphUZw5Awnkx/kO0cHYJBEV2fXnyAdMYp9bhxuF/S/dMKjOxVwNu/c97beOAuKnssVCMIo/8QJEmVa7tL/dpYDHR0niaNRcT1UJrDg/XJIdeIxsrkJaT5so4NELKU80wx2eUQ7J6AN20VRGnReABV/WNNumgooI1VpThx7g==,iv:X9mRFfHexcmLfjYZ2QCco2X2TPdZ6R9q+at+ubRyNoo=,tag:LJbk/pD+fm6l5xV1gzWeTQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:CKk88v0sg31TKw7eUGG52P4V6ZKDdFTwY3nqq/helB1Nm2hdGe/Pu8wzxWotWS84oaUAggEJVjRSakPMQXhOYtm/zQHiWRLJPvlLKeLwQ7mlvO5B36Ko2+CxtPSU+o6nbr50ZiFAD5xhVHYGiJmTIYBI5OmVvUXGlqyQQfRgDxOTXV9/bpWh8VKUuo6ihX4ZKGOtb+78pFrW8mJXk/rpRAcG11ugJuCp0Exz,iv:2VVJ5uwsWCJRvQKvoxvAO6X/mBx5lXAyvhcuOnvJr1I=,tag:kowePdVbFOCNMedBcpxEHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17yrg4567h6qxz80uvj0h3lxgdk4f0dfmd6kf7xzg5hswtlngsqjqe9fj3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRStxWFc5cHpEUThGR3ZT
            eFEwaTJQNVhzbU5nMGRNdklZbTNic2JXalI4Cno3VEMveWxYMUt2emI3WWZrR0x0
            RTJUTGJqMUQvNlozZlNMYnZzdGNjYXMKLS0tIFk5WjNEamdPOXZyWVZFTzZWMm50
            QWxrRXhldkFsZVJvMnZuWGM0WlA5TWMKhYq2hWWPxFRp1wgOSLreR3d5De+jhkvB
            qPoB5m9rr19vzclIob5c/mqN27aHsMdwSX5B06M4zJQyOQ0hNGYi5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T09:11:45Z"
    mac: ENC[AES256_GCM,data:UKwFs1Abh5RqsQjzP6dzTYBPy1vQNxh8y5cl8H/NYyCMBgtgjOpKb3/2v+EZB5JQ0rE045rF25lJ/QF2z2DZMXciD+ZQVVj40bdm/FnLvY+hm9GL71NnskC9aRGFR4wZL21fKch5rHsIOz1h4rc5ZtURqJmk1ksVFJrAikuGomw=,iv:N740obgu6YRwQF0NtMfpV4ix9R43GnBt3xbOUHS/Ph0=,tag:0imK6I/yvryx/lnOu8TaJQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
