apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fVjiMR2QBTa0u9ujksftJAL5/L/EjVvdXx+KvF5juDzNOj3aH9+jGCRLTls9BYbisCQ/xALMe1gLaLsSRQYIkWnRLkDQKSlmJXjVAn2TSlPwF01Ky7VggOmH3rEAIOohM3zSC6u6s3LHC/fdTcGeNr0PsT1OAu0uRhAb4DuP8y8b7uUjjDCng1oQ6hZsRupY8DjZSI/MiHU4lOSudzGkxOf6jnQ5kxL89AEs6FSpwg/Uk17GYS2pZj5ZqkiILcw6omKQ0uQT1aUkF9+0E4UO+2GqqUR6qO/KCbkgJj0ddlH6uuv5R6/+z36lNQsE5wEYwBdGAVrUpZmaboJ2F7+JetaIxvg6u11ktQXgfkFnAAzZ/VRDPgeAsuuZSQHcKFmm,iv:P76A6TO+piaMnoxmn4+TegYeJE/361cZo2Uvvf5GZHI=,tag:rLbqj/ZRQvwpnkNF6YVu2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Sb6ad6ACJon47IOTSH9tE5yplecY2+AyCQak28TwnHLZ5rKxW955989cxQKZbg1m7zVq8+JFznhLLqGqEqXClTsTuI3MHSlG7Av4IzKu/lB/m4SgD5Ec9JfwW/G09LyN8xEvc4ALeNKqh2vudjlgYiqSHdo3crJpqLTcKiAVMGBgqMtsIxbEiMmtmOc2+CjESMdBhkY5wZ/W3Kc2QfJPt+b8YpspKDc0SfOJFxutn3qwpLoSd56vtOh82WmR36pdk/8/K53jq+X9GQ1BOg==,iv:jjvu1ybRX27GtG+6m/RFtURVMh3TUMmj7Xmbi5jBSWY=,tag:c1KZ4qT4nCY62PTzppM4hA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Hwk6Kwr0WsAK91TBzybgCT+hFmVfwAuXZ6TR1URuFRC09IoCZ8E+qLe4Xw/pXm+5b4TLb0qSgJGaQlA7K/57W5bJ0IinBUOOacDwSUtuGIR+lYvAMAHZv5FemqKRjGMCHmyVa6RiZQJZS87EW7hQl1VTGmxjhdZvO77K/YswPbF40m/0J1UG5qJ0XLAmv4Qpenpr6clw9Nnlg4VfRSqaxJetGbsuCxj6jaIA,iv:912snuMsl06rKOYBw0qoZ7d0QduntUtuNgSXlGTxYY8=,tag:s9HKnYo6+s90nraT8T+HBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRXZMV3VPYWVQNGV3OHBI
            a1B5Ynpab2ZEQklaUTYxNzJReGZHRXBRa1RRCk1HcVRBa3l6SmUwQWpFQ3JQQ1N0
            UUxpOUs1UklJK1VvOUliWU1zTXQyVHMKLS0tIDRqTHh0TjNqTU9TUk9ON2JhbWJj
            a3pNTFpXZERoSUs4cjhtRENhTi9udTAKCScBhE2mZOJ6wHapwApd1+g79gXHsVtA
            BZbf78RZi4287RR2L3zfYEXkt/vLsxx/iyfE2Pdx288rDhSm8u7QlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T18:13:07Z"
    mac: ENC[AES256_GCM,data:h54wGrCAS/hTTzDoZyi337YGa4O5dqZoa4aVRgQV2SYnyPT2R3nZ5TBrqMwVoX52Ae/oojSNpgjuKkHXN4zRogyVHLsZ4QhW5QwPHj0Q9l/cFcE2IF28ccNu5Fpn22pwTYECpIa/vvupU+KYAK2665+FNNUiyqv/mxXNPX6tDY4=,iv:EhEJjqB7Dq5FrLlYPoik5P6gmYlH1iAjJX7xrUvRPcE=,tag:tA8ro4cdyJy9ahPxOMVd1A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
