apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yYxbpWzGuN+UA331d7oQestUl/lH54vDMH25Zk0UgOgMw8+EbyDIkojf6kcXlxbivrGKLx9T6j0obemei7jkEarlp3sJ6HFHydbuzZDueI8J+3dwHEzzuvhBtc/D6lw27vvqF9Fc9gog64Az978WxL6gjslZ/Wkl0BGpcAB0dgF5DP3vqWdIHYa/aVAN4nvcBZdgM3wK8uyChB0L4ocy4DUE2l5fK1+McIpvcGUw6rJbD4dBsxVBCDUrrUZmCl3Brl0K1PrVULLNfwGbrighFV+cQwhmSv0aoBS0HYOcJ61PKCdN+fh7zVa6Qn/3fDJXlD33zFJ3oft89SbkKnOoxHtz5VhYW9fJHbziDZnUOfz45dxusw5lyWNsUVtx3hsC,iv:P1iYDNqIpzL1ueGrQhdrW1GCjQ87o5uWl1eYWnx+6Uc=,tag:si3tpK8emaIPkTsrzlrYYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pxuG6R2uc8gPkm3oPqUWiiBpWREVjG/VNxGnOXd/JUdV9mder60jCvb60vqyuYM0yToo6TYLPf3jFdDwjTLN/w3EYjNB7hg3g5Yn0/eewYqvDmFQWqxj/yyEbhARfpsLgPixp8Lu3gsUIDQsFayyYaGsrIgTFJ+j+kADC9RLDc2MbT4zDNtF7TJ3A6CjAtawJHhCU1sXpimlZV5vvTMYLgRGWl/p6KC0963bKIerTsVdbe6edlUVJrW+394Xsr5XuUkvRP1Z2Djbt77GGQ==,iv:j/oD7jbvmr+vlELZ+Mkfr3efm8wMrnHjv+YsnYuIEiw=,tag:nnNmwKmNlv83EVTE8U1F3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:7DZiMwW2bAwpHTC0JGFlMj7V7YylTOZUjKOEhQZXvR9YlWcALtfCys9J6RLdWB2SseK4ZD9f3CHzahGPE25MBiwuijcgbkZ4YjD7uSG2SMarOdt7AmQbZi7HZsvoel4mwl0hykUIVSGi+sQAUPv0fSgSqePhFKlESyzyGvtTHjdAEEzmVVIVzkI/o7ak4GXaPNV6cDm5WV36AdtRbGle6/+wlvrWg1XBy0l6,iv:K0BfbvNx4TGeXSG4mDnW50xDJnWmsWtv36yoPHCxv7w=,tag:G+lIoEZacAnzedlJhXbhtg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS08zMEFSMlVjbFRyUlJq
            dlhZR2VMeDRnUWVXcmpUOXhXUWpYV09xSUNrClhaYjRCMHMzcjc3SmpPaFIxanY2
            VnI4WmM0NllQRVJKN3JPUkpwVnpRLzAKLS0tIFdURXlQSEJobjQzclNzOXh6RDg5
            YmM5SS9TeWFTdU9PT25wWW9zZ1ZLaW8KzchR/DGf6iu6muyn4GyIoEx9Ca4y38jl
            je+SJyUAEDHdbHOcvQbUfKWuGJhreHtcypaEcFVvXJ6lbKzTJp3VkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T06:33:51Z"
    mac: ENC[AES256_GCM,data:xtsl80+xZjvI4Uf3vTzsTvAcRU66Q3UbqNQ0cHKjhWZCX0GEh8y9PRaFygr0EqQcK8UhiOFBh4nhLlUu3qIVBarc9lgaVRTQYBA+QNRnC1YI8AkdlXFb9alfu3e/Zc343pKV/NL2ltrPsT0gEaYFRQ/wm/NE6yUOla3Z8di6v58=,iv:q9F3N/dVxxyHqSBO0jiRNhrOKH2ZIVqiKVeiyaLNVHc=,tag:BPUGJaNW05879eo9Hnlm1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
