apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0+fy92sYpju2IPXAchmvlzIgeKA+yA71KBIiqf0beJeCz8unuHUt71n41VvPysXvdaXXjufNDesFOwn8+BKWrLuwvet+bsFJTeOpoaulETNPn8Yj61IzKCRX0m2B8EL0ZyWylBKtJ2NBPzwESbCODCc2JxTb24NqOPfkmB6vAC7rq2aPrL8ImJw1zlZyHyiQH9hPTWfjBjBcfv3PDlGfXQtZJD29tgfiTxv30RdFCHkOakyLU03xf+ufvIXcJcEHQ0Mof3P2Ydo29bGwMWSyIhCy4XAAQpShYT4/nwPy9QJsCvVUkybH5QFsEfOtN1bfrn2wvgglSzQP7LJ6kXiuiWs/TdnZqqNcEX8DNgMPADaLDnfcx8g9Bo8qV/2PeT3F,iv:pyZ5ysquiLrdQFwRqHlOgppuT6xmzOO1OKXmkjNpedw=,tag:8ROA5J+zTEUA9DIHa6PS7Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:5xcLMtjfr/+CdlKqVF9vXAcYWti9pNWGQ1as6ELQLN/9wuHpkxKsa7rPJfZaSlqd2XKwGcS3JmOmG28S5T6l8mySgnL4Br66wKzbRyzSwumWrkGQ2s3OZaGUagxYZQ+dn8FOB86e5A3ISK2jt+vWtw5a9t55LnW/UgPRUh6PZ9qyiLQZTBNq9wxm+AtPZyjD+iCQLRtsVM8Gx/EZvUgcCQUurz0BWk/bIRCovCMKAqoj6WlevIvNJAGlL3VkFvBZO6y9xeD3L6UgWdJfPA==,iv:dB7AWO1CVvnnzPrXZJWOciqBoxB0pls/WXVI+ZcY6os=,tag:s3XfErVbh8/muSyAAaT7/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:eX0VYWd+VAFH3XbFkflL8G/+0jWxCIszbDUqVesXjPL+UjS+iiyfgSyA/8deXl/Mc4fjtEtu8hej1ln+UYGnZcmyjy5ZNylcHxV4udl77hOn7X5kGYW5kDYhuQW7YiSr9Yu4Q8sQ6IpNKPGgwgyoYbROVjQ71gsZDM0dTtZSpswmC9/IjSrw6rIfKZO0c3KzYZvSaaow0z/XccvYUpwXPeDD6/gnHw0A6nef,iv:0d0YWhixDHU1EdCRccgGQyG6EnB7HZj0MDtDjaKPQtE=,tag:FJJh4AmG+yYIsrXFv5yPmw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVlIWTFmT1dCc3dHbGFl
            cCt1QU9QN25zMjdaZThXYnZQQkljN05EMlRFCjRuNkw2SHhqUkVULzA1clVIQWt0
            WHNXM21oUWMzWWZ4K2pWZWVEemF3NWcKLS0tIGkrNmJBRy9SYVlXRXAySEhUczNG
            cm1ZVGNDS3Q3bk5OK1pKVDQzNVpkRjQKuFpIkXfMAC4p8fKaTh8xU1S5NBHZfJ7L
            6R9bXbXNJDY254uwsAfZgaleuTbcNa+T4kmt0k8jBAnDBt+0OwyTOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T13:02:39Z"
    mac: ENC[AES256_GCM,data:cAUaIIAZgDAVwTYUDCJ2s7hgJC608eB9EiUCamzvlRh5oKQ9Im3BuZTmn4oxkcbsFlL5AsNBdKEsaSafcuETB7pNsZ7DYJmFFS5knLzB3z7rW9uDqnjCekGJ6UHcafsz7GwTXzedSMuQT4I7hhcl/52CiNpScAdlg/VbueruYvg=,iv:zvo8SkvDvKhrluPz68RZVtixbo74iuybq+T0uFN3kjU=,tag:4Jh8PB7s8cm9BxxnPYHmyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
