apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ckqsEAxP202PJHlRFNhVb57rrmErxoVHDw1+eIxpTyNJdkRhwqVyHGIMA0sqN7T06q7UhBRzO98LWxTeoOqnrMmG8mKaMf0gTHQCQTa3OLzDJ4wvDlcyxaaxwOHcq1p0d3BLnIvMz8uA9vkUyzOb4fatFakd9LFcSO9DnUOpgKSy4eY1FxKPwjGDjuQOdtZ9zJyk7geDJ8ZZ1Z3rVzNpd6fBSFSSuS65s9OFmP8mEodvGd07JjjPSaMCEsTyMn0mhmhU4YcyfdDPwuGTxRF3zHXlyDmNTkZhdOQQsQfGn9oCIlMxBDo4pWccX4ROkwTP/ush7ts+EQ0RDTtx+lFlS7uh006uup6tI79n4vrZk6YZMT150ozowrZxaiuxsp06,iv:+r9XJSoKgmLInYsP7Ep6dbO8z7bGyg5pm1KFN97WhBI=,tag:BmzKZ//b3M6keTELUrWsKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:KRIpud2+khpAWuJx08F9sziePSLdguz446bvdxXRwcJuAJUeK7cQIRkvhlojBZvMXB1NkE3guqLJjVHcOoHoZC8rtlXDgYs9zxo6Pjf6hTkrXtUHjiTKiaWT+7khnJcDhn6l40jnacfGcTqwID15Ps9AApaa7prd6ZivJYr/LyJcYoAxNfYS4flA3tscXyDZSPYgC9B83CIGN3lZ/+iXAcHkMYZh+uUMcooh++urpgeMqANBYNS8Ku/nuqohxxBxVfUAuZzPwsCrnrAHCQ==,iv:xaaZrK39f6EVuLPL/zw2F+znttoi4/rMkoJiy4p2Vhk=,tag:gET5Z2LFRaR22Zf7r95pag==,type:str]
    known_hosts: ENC[AES256_GCM,data:XEt1ZWRUeCKSAIfLzrS/ZWQnPpHwQ+CrsQpYt2LfxHOJ4sJiz0biByMaxASE3J2TakekdJTAgwUoEZHypD+3PKeBUQfy41YdQMJa6bX2zOKNnC03c/wRp4WRuPx5xlmiujnZP2pXe1vA2+dB8BWNJOOPzTJeidKggJZ1XUgwGm7ltbQnrwoGu5x5VRIMhGbffIFAoTSbc2lKhnufFhaXxnhlLLSWWUnAhYWD,iv:f6hAeQiRxy6L0LK8llKGrOPcRH1XnBtbicRwAINcgrY=,tag:sxiEGRa+yhxD3mpmahZ6zw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQUYzaDFxS0cvek5qNm9O
            dGVab1RnS09WdmtSM2RzaXRIZG1KZGtrYUV3CmlOUmJyRVZDUnRsRkQxeFVySm8w
            a1lOMmw4ekVRMzUyb0kzMUVQc08wdjQKLS0tIFBMU0EvakJBVk1jemx4anRlUVdy
            WEJ1OWxQMFNpako4QXdZSlppbEluenMKYBEe98dkaMdXgY5ON/1RzA+BBKDn2p0h
            ucJwWK8/bNSOgXKR27mJD+5X4yvkL0ssh8bQ127Wvl8iSqIkPBMTug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T23:57:10Z"
    mac: ENC[AES256_GCM,data:S4pPQLPkyVImPYlOoh/wNHN9/ltB5MsXWs0yzeQAtjAavp7iqvrhc52G/lQE4/FNpQend4bQlfBXu/4uEZw2A68eooE440QCWx+wNddeBOZsHpvExEq2WNbLJgvMfo+0qo/jDGBx2dMmqMbVxBDV9kWb/ca76dnlVsXA/IXZC70=,iv:YBqEu384wS2NpVYPiYv7zwq4BOLz1F4tBVCKhNPOk/0=,tag:g9n/qvYl/dFmbJzsKVlEGw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
