apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:if9cQkI4X7cduDAf+QsHFT7YfjVqcQGKemsCfM+2Dl7IiGrisBr+AX0iDEdU63eSKdqQ6jHA5qL3q0QA/ufeB4D74c+g15InGsxmghUMAjrwtMS3rkuKoWcIcuVONw/9woGQi0OMaadSWgoaZDD+/BTdwRN/1PyfEdWZkDws8S1A3HDPV8SWcEak+yVrBzAfRETDWwHeNbyWzDJjJCRiRBYmGE9t3UpieumsQPlipzs5bAtcYBzvZ2tGS8op62pjWKiSn0jrm/1sYy8jVpnZbEhBYfTEChkoSsMq16P7TKLGd89yD8gWevkW4yqC6OCWj9aTPWj2RLgtM2J5XloR2VAHtH1fg/CNtlAEOOVRoiPVhmaPgfNMROtMnMhQhFGo,iv:XMSRBSf+PNEqmT5aNNoh/WKgjFsA8rUefdpbOewJ1zs=,tag:YpreiABt9chKQCagj/JlqQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:XORDRNi+JIbsK+d0sRmoE/ycUuaHkr4iN24tkF9vBTdRuaWUsVcoMnb3py1ik7xCL2cnpOOqfcigm6VdygqAcNXcwYUki1a3/SMd2Gyo1O+0nYKr8b3sQaJt/64lEoZrnCXSMCFrRhIheCVG/t1C1/psBFpjY7wCIQ7f1Cy1TT0pUAq1sD9ACyM7Y3SHxrF3b07QPBkTkpx2xsHsyN1JgZ8/J8N0J3PXjN4PfNtEUuSqrgVtVQW+OgFDtAtbdWXE2ae1hpjEHFBM/V4zEw==,iv:mRa5Hssr4qJpe7/KvCLMHnYP5by3NQdXotlHpEIP86M=,tag:zrfHvMl/R3fdE8gdEHdRIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2lSnMY6qK2KjELc8F6vxzUotRiYg+JoKXyr9AulUGJp29D40jWyBJESWZDpxyIX+4GRBjCzRnHZ4//vs1rg+W4uaghDTgijL9BOWXuYz9VlfAKvG5nSSd4xLG0r194HYT7rgbo4bb2dXSL9FRJrdzZAUBb0Z03Jhl0RO2IA/HmJe3gHdPOb2xvFrP1FujllkZE18WmfTUSkC6oYH/8HAykMKgRlhrl6JOXB0,iv:Y0Ibii+LMgmbfnbc9LmDXze3ZiHvSMYhpDJJaARZQa8=,tag:fBPY1ljJ4hQh8fs5MJSCXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T1VmUkZBc1BqYXlza2hx
            UVZKYUpPVzRDRmhKYThUWXJpclBVWi9ja2x3CnU3WnpPYVgwOUQzVGpJbGhDbkg1
            clJDc3lNZ0VyMisrNHJXcCt2UXF6REEKLS0tIElUbkQrdG9HY1FuVlpZdFV4OWtS
            QWxTOU1ua0lpRFVJcGV1V3dVZ1dZMFUKLR7NIxl7BYDqK3HqRJq0IB/DEdr6OQTO
            I/4iacEVc46J6JBCRRynpwxGJNbPVth8abfNoGXIDGZs+onJyXrhqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T11:01:57Z"
    mac: ENC[AES256_GCM,data:XYdDv1z2QqWkldLF7cfzHTamuCUG1RerzF8FtyPsM9zeLJ+uB5boazcDWGvDXH022kUVSiPRBAaupgezNq5zifzTrfilf/nsvFJH7JgY4uH39Shs3rt/Ln5um0H10rWB2ORRHuzbMSSJf6ZQz7Pgb9WhrGz7vqzmXLYHLg6Br0o=,iv:hknq7XtmUbC7eZb9Xpp9UMhUjiQniO9gP/L806XJ+gI=,tag:BgjGGm4culNIFhUKloklzw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
