apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z+lK1ja6xYgVo3hRVE0rLzYRYM2osJH6xWxkVCkc0AVK7uFupydeluP8jUSxIiPnb5vAYbn6IsqpHgnuElo2wRgtPD1PnAEuRM5oVKQBOaJJ/CmEo7zan6lNUPt/Z26RPUk1UL4X7xvpO+8QXQZs8wFipTpte1NLZlh1Uqo58WDJr37DGbTwsrz5BRtnnjzDatLxObj+wjR3ukLhjtxvemMLI0WIhDfsi2ijJgE3YTYPSY6oTphH3XfLS3QCp2UW5ciAwmeKc3kdjlTJnl6+GNYcO9n00TCXmPr4ah8bls6p06OsPVUq1Dev/0GV2of2VjxqyItC/4DPpNWrkWgNVLl5wuAENJ8W1Ss33dlR8y5oCBp2x+Nkc9Jx2gX/daLw,iv:N0AAW3Enh9/XEZNlphSmn3gBcNCNSEV7V0IJ268aDv8=,tag:jJTdKOmDWHhT1vJMPZaJEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tzAw0YZhN2LEKbhT2N4dJ0j01RNtOD67O8Q6pcZG2Yr+5HK05djXqnJ4v9F2JwjLOZHna8BEN/aSqq0ix16vYlJsAd8ky5Mp1+/zw2XWEOIPhS2LA/VJ6XC5nv3OTwhY3x8+jWHROnLfoy+C57VC6g954Fj7stAXcn5Im/iSSV/z+tshZVDRa8X5YeefWJxOv4MrFbox2uPPKoHLtDooFkqL0o5b6irwElIxWXiAj24030Ye9JL4SM1t/KUssW9A/IfsdcFXuWe8HG/rXg==,iv:XdgnTQ7O+v6Rzaov4UqBuZlaGZD66LdYKddsf22vG78=,tag:BMdoF2my/WnaLkmwEhgtxQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9E7bVRtsxBDG5zfMU34sorvyaAirli9IogiMEE4E528+NdFQ40mFwsdh3MV1mrVcCZdmZ0q9PisQBzM75kayGuK8QuckMpjiWFI2aPKagEMuRjKltHVAWbHeNgrSl2dySXLsEfXoBoBYhH80f/2rZH//K3/eVWUFhDpiAKMZjgJeWmB8CNmxZMZz1oWGpwyxEI+7T0ImsNPxeyk3f4kb4sdSktNHvJia4eaG,iv:Y4eOSwXosIPYg70iNuLi3EajAcVeC16LsKp0xhxfdI8=,tag:iON0q0q4wxqEAQdmFXdcUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbXZQVThtY1Y0QllXOUd3
            M1hoUFVZY2UyNEk1WmFsL0Z0aWZEdnhtVVNrCjZSYzhzSmdQeitWUllBb2hSVmYv
            WlhDd0k1MUNTc0NLeCtPOFdPSnJ0YWsKLS0tIEgycnE2NU1ORlpYeStPd1U1cEpC
            cHN1ZDEzK2VkbitadlAwUzBmdWhCVGMKBNLa3brndJAXPnSCLdcQcSVUAR0We8p2
            sSwE0a2Dh0c5514roJKwyUPHN6G7m7v1mpLQPRfn/iQvLx32B6Ripg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T07:05:41Z"
    mac: ENC[AES256_GCM,data:tIMfLRL/N1xaMq7UIjpd10kY9fjownF/cRzC9h7x8EUijhTAyoPvFH7TpRW+CSTkG3Nx/GQrbpZab0eVdl/vVvI1SapDLrjKEBReJ2k4z8wAdfMV8M22gsxXE/eYRvhkmuwV4C0OA9q5if9pFLnWCGRHszEr9AQ7d2VXmY6kj78=,iv:NWv+KWs5nzdquQdq9InSTCwt/O72xOmNJreD0kW1OnU=,tag:5nVGCOSrQyqXLciHVgI9Jg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
