apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TCXhY51h6ajZBICjI2zkBQWxmRLrD0Iw+smO/F61p4R5aJY7QL5QvHBVNijQj2uWKr7UUDH3a4nbcC+p6RpgDKsCAgdFXcQdY70a5v76tOZo56dvGeVR/MUkZf1yYEyxsKoFLkClShmFfPJ3ftBSFS6CyCw+mna1sttP7RbvQadKeeGL2cTN/mCGLvLChTUv5eANgEVxsJUAhlv1hBH0uF9gimvrB2c5fGeOSK05MtfaLaQd7do3TFAAOzHC1wudA2bJfVVu6jVv+BfTx49+++5KpThK4qeuUtgBecycNiadjmkeRQlXJHEinhBbqdkXiBO5mZG8rqSIG9FCWGCG+f2xvL2ttoZ4mlkJ6SibgCM8pCbcNpm5kJyyU/2nByu9,iv:xrC1y1/5ab6UWtKVbZzbTYau5XlqTgwtf9FxWL599nU=,tag:74JgzQU9Sd6RcmC21iZ0Xw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yQqMbagNmZWnr3hMO4tEdxtr4b5YQT09kexIhqBBAx3BsrMFz76EnB8Jg9aTmOA4ipqBjYrdiJGBLyGz6SHGjzlhMz+30g5HJJUjqPyYCYnDwxcwAc3hNGEG0iwfmQjCW1MY8vsuADCO29bVjDfRNEjqW7L6qUvUv09yy5DrUgan5lOzq+BQNy7O/OmGx/inULrNOj5JVAek1lTe82kLyn52p0PDnGJTP5eOfh0ANhxHqVL5/rJ0/6Zs4nt2A/Z+mALhbhitW7AFjU6GwA==,iv:JxSnuNFXv3IsDSU5eEKPUCwJmJt561NRWLYRi+iZHdA=,tag:MBj7YzkJJxW5pPPIJKpwiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:GRZB0Aaiea+d4h0COsvhKXwldVPs5RDpuqauoaOeYmnpClAbbZJBG3aLWojkBOEvsvWLFFBgm7duVOEj5cN2M8JQ3XAzOe4qlsFHfzWFHWQTq1MzsZrpEgcF7s1GA4ak2O4M+685mQ396U0kHAkbUTtMh79NKVOfZ0TaNhHEsu3s6llNSKEnnObCjVVCqfcz4z8jVpU1s9MF35bBJMdmmugFO4Dn0bJWWv4L,iv:FWz/tSUbOUP+SBW1zTbQzv04p/i5XUtlhoM+ts8T6Ow=,tag:314gggImE+xD6DjzqkEGwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRWg1b0xxTmJyV2hpaDRp
            TGpCb3pHYTExZlBWeDdhbVIwZHhTMnZrMzJNCmJlVHdPQnJFY2VNMnJYZUZHRFNC
            Zk43aWgvSVVVTUhUUjVwczhicCtHVWsKLS0tIG5vZmhkOVptYUFpTnNjYmdlRkhK
            eEExMnZ1aFVIa1ZobjZaRUczRm0rakEK+RiVhY2xDMwcXRe1pLGQqeXgv9e+q7Ok
            BlAD9dQHbf+AZfk8oBMC1m3U6iXBR6fcshmGzhZ6xLabTMPCLsBubQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T06:33:52Z"
    mac: ENC[AES256_GCM,data:SxMBfdyCpxICTMmNn8CdeA6F1yLPPrnrk0lbnX9/FXTggiOXdbN1SYiKHxt+eWeVcnpn7ilo1KXBz7U8RlO6JXRbcdE5haWvEH7s4uN1IxsCHhwxzvkiAwBoTm9DDeLDve1FcTwP+lisEhgJyJSJpqdutCGJC+1q50PqI5P5dh8=,iv:rlh95BpVmOrIUA9+YS5tpMq2EGLCc4CBpnW4eDy6OQE=,tag:42BEK53+/13tR4agY1/1Ig==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
