apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qtRs4VwuRcbf35IfUsPQkph0G6rk1Qp7rsjQmDXiiEvCQyKDA1ZmfH5l9AUr2CR0WfqANvlGidufB0tGOBQTy1aSwjGN2UoDiNbSaJADJK5F5GXIEkcIufR9SAlwXmw9FqTTzgszgb02dAguYcE6fdxytdVXWAGenrTbPPrxidAFsePNfQPKaCUhcT53yeomfx1FWsbtMoyyRf/5P9ac9huF4HjdTVavSUQ3BeAmw0DDOqiKUW81HevYTGiZELAiEIYaw/nsuE7qVlm7KK4/N0Nq7ZhoZmN/L460VGEPhVZLV9JVs7a5BC9tqN3QHm0EgVz0/9s2e4T20p2wukleIQ5RJ7eOOK06QPxan2r2wl0K6KDlWvl1vZp6X3LyJ4KJ,iv:3IMe3v35oa1zW8PsJbhZ6BrEpFdKZtFTN8rDRjPtdpU=,tag:5nGIb4wOnlxxp8QVLI1mdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ndTAihMCvrasdgVkqduWmQQYEb6TV3KP0k8msPyvUk+pkiigFwCTASfDOMV4zIOsbxe376KC1IWjg+8Gx2CwEqDFr7v0tCdUgbcxhmFgsZmpmIWJ4ACFBBQS6qXHkcxxThAbEjOlTcZnb61BBJ9Uc0naEAmUcPNN1z5MWdPACaKmkCz1tUQqzPx98+PPhtDaJ4ZRqaOqc0jmWLng+IWSH5H/n7X3pg7ZgQN9pW1pWuDYueB55G4KLszLbZchNgGtFKkeWeQ1G6z4SrvZSA==,iv:HqfYXCAFnxnzG7mGJp9zNLZZ7V/Guz+mZ0XV7Qr2YnY=,tag:p1K1rmQGCT7nLVIyiY/WQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:k7CXTPCLe1tZjVaUYy3Xdj+6SJJkn92VQ12sl5PH1JEVHtXjxLuTv92SWwoOJzq1kzRECHaccql/CrEvRJk3I/bGo9yz5jFrbWB2d2H9ce7UYZqmS+scaeQuWUJ+iTwCBoPJv+FjISMZLLv8ZDzGtgFq1NzGnaDjEXpvizmnySSIqktqNbiap9bUvhBuIHV5IcnGrtP7kW3zdPCivx8V6j23qFY3sDF/rYeA,iv:XCoYFg8vgWrxpdsoZbTE8JKgh2gEX9tmEae+qFDCxSM=,tag:urmpE+K/9BZ60fdsgMsgIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV29hT1BGbWh3WGdlMkQz
            R2pBL25LNnQrY1RlMVpUVktEOFhIQUdLWGtzCmR6R05uZWtIdWU0OXZiTXhKamNI
            T1dvK2p5OFZObit5Z0lSbUlSeTFlT1UKLS0tIFpTczlSWm52NUswZjBJV1Yyc3Bw
            bXd6UUZnbGtjU3RZY1JUNHR2VXdKRFUK4Cs/Nm3d04QUawe6OnqmJswzJVS2TsmO
            tKihz8Y6v5lJLBqLUoKAyPQIN3h6iFEw/Nu/kfymqmNNZRp0CfF0Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T04:19:15Z"
    mac: ENC[AES256_GCM,data:35+HPC5cHbNG1rePvETntu3cgxPPO7vOAFvg/sLyHAekfj/Tmbj6RD5YHMGw9HH+OQivHjHhdrZiZKWzsWMhFViwTRrocOa6KDuKvIRRk2v6v/T5PCsbevZs7dsaTCXgv3e7zR51dwZhS+hpKoM4KcUxxJaGpjeEsziwcSbL53Q=,iv:+BNpoAZ8gBhIAbqr5+9/7+A6iFBvbrcs4hKDYHlaVUs=,tag:l2jCQFHXS/cig/TpERnvhA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
