apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9qOi89YsoTq/QLOalf+pfYEHCyVOOMSYBle5TxHeCitxWRkzWtAdvP6IAzh8I0MblIu8gDJ+yD7KHkNlhkMCT24oLo07uMuPUvtC0vawz0SaDiiS3y+B042/O7EdakzipiaPM1X25sEE2e09ZcLcZzlW0lqC9pUPBTw1KZ3pQ8nDX/uUnmyZu8KjA9QlpUWlIQ8ziujlfrLfOcwblAptHCMrvHfwgHRVii38h1Qhf8uYBKhJ999oAfJ6Fb8dDn42xt/VaZ8tuPYRX6+g9555NNPyWeWBSTeZWobyxPDstUdETTp49vXQCVVGlFZWU/LBHg1B6BRyCPYSXqGgwUffdALK/W9KCsA1xp9fcpuDkt6Dj0SpzqHgVslQq6OPImyv,iv:tSOGO+3u7DjqI9W8e9malpKZr++fLOGwUSHnz/wqkRo=,tag:eZBnteQ0U826zXbXEK9K3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:4FPy5lB/S6JGXFsUeFaoy/Ijq/OoCMULsfJc/lHgNcD1SG6uRP1D3Rt925UwvxguGCp0kG/idqkndOH0VkL4JdkQbTrIAQC0wljJTWUTeGFrkTcuKVsbIANMCeDalQYKWbEe6LdJCp047tBULvhBT3ds7aHaMN5+HoNGiF1F8/SemTWbtylCfNV+pXJSc19jdNbQeftFvf+sUASq2RiAKeyFWqW8TsTlrD7xaQqALAw85u5mBqmC/DNAoT4iVCdrorHssHunVUCSHJVauw==,iv:KZp93NUMTA6oVLI+ec6H8Y6SRxhXJhoBLiEaXL16M/Y=,tag:HOFO+ShPtDiZvjf+99sfZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nz0b0gP4GVZfXJgXXdAU39TX/Ttca7KyVunXwekt53cEXLmo3oG0njAmJTbwY9lB9DBSQCOLvr4FTy447V5T5JLDbvmy2daLr3JXJ2gNNYjM5VcU3XpfXZ4AIYXEp1Hs/jY917/UmMp1Qf9fE4j9G/zrhfesFpvOkaS60nyE8F5bnglTuvfHh3rH1MM0uRxkMP85wMQpG4Nn56IpuAY3NUaUaJ8FotdTYemO,iv:LBU1Ii5qgZMadfh8nGLdkc3x2fIAbBCtQy6g2w8phzE=,tag:3q2kc2biAwe8jAccjskUBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2enVpU2hGQWxSUTB3clBl
            aVIzN0FnMWtJMjFNQndma2xBQ3E0TVFOTEhnCjlnSmJHZW5ZQ25jWlVHNWc1d1J5
            NW1rR2JCSjJVOWowV2lLbyszL040bTQKLS0tIFJ6RngrVXYveWRpaGpWOU5aVWd2
            L0tnNkJrWHNPd0RMWE01Y2o5Y1gzYmsKm8jzpEBIPrmVASEr6gWe9uf00AaqO1ro
            YpnolPhUalTASKvtumuL/NMyEbKs1mNtLMtepk0095EUPJuueRLE9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T23:35:59Z"
    mac: ENC[AES256_GCM,data:fXZDLOeoQPCi7pcQJRHDkJUGL0O0Er4BGZXAX2vzPKTvZN59NYIPRzN3s1OcOuodAjqVuXubB5VdNanfc9beY2Hw/BczI86pKn9FTTq3mgPBOCH8z4Cbrcow0/R0MP187zCCwknuQ8lGmZxXnxU8Z9w6qRdz5qVjgSX0kpqjSz4=,iv:hUMJUlAFUu1Si+9QJZWdE+q7o0hNZ6HQ6pkmjRCKIK4=,tag:Sgot12ElhJfUPRUaM2TerQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
