apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KL8hUFV2nIGjv41jbLDjZk1t4I32xHe8tOWhIYgovGp5XptDXnjIH4WL9bqNxaSIxKq7Y+tYhGMdqAyNRbTB0snl70y59j24JtYZzd25sg4JgccFr5FRQdqYjrrxwBzmxNdsBILMaL1AwocpnH+Yh1MUgpG2FoXjfUbA9Jh1nEy/IBK4mlAzY7e10R4dX+WSTF9ScD5Dh+U0VeASnSfbUKNbHLToE2PUha+O8H6pOAUK4Gb9YFNXPHNfeZ6EsF3mGhYJVWXd1aeKcNsDr965MH4jwMfO86QPlFzH1J3p+3h67QUzBt7yiWLRQYjLyx8Gz2XUPllg2b3o7KOC9In9p2iPoJeiH/5tuxIRZ9wlUpDoUR3qDGo0jMqnuIopvHZ+,iv:nsa+72kihgcHlxylW4ZrD4ixJKC9pM6Xlhs6lZqqhKM=,tag:NWBc17ksOSStjNMT5rZKFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:KAn5lXxe7DwQRFR7GzEZ+kkn63qYoJSCTj/D6dJ6LVtPcP1Mpoc4xuGt9QDyMylpJT/uukVOObwJPFHad0wp5/PGhNSjAyzq2PqVqubkd3KKbq5gWpZLcdaPnTEJXDc5i+PlkhUM8TEy51PEiy2xGWAFjloiKrq1P89eK/1U+HBH2yNVV7/pAejrW7w5aGYOU5wL8ECJ5P1sCOd1g6lK5n4x03iynom3b80TzN/q81rrG9JAZzSoJ/VC4kBpq6247E3pt+c6tw2HVDC33A==,iv:px/DontpWwC+lNaTVw7g8Xyv6HVNjyO3gN4TpBFPlv0=,tag:2rIVTzbWOUaKQbUsLSqPKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sqJ4XOQuURUcYw6DO68pWI7Omf6Xthtm0ujbO4cW8Ill+22y9wUwE48caouaHC+ZMAgpQkXKPH57FVaJV9d5Ulje6vVS8DG88mzWPtEBmPB+r5IhNtJsbvpD9rxvmtDji25Cai5lK/q4bSzWTTv8GlDqGXYjT27qaxC/tuqh05S9RyHd2+dW11Cf1FL8JMP0o3qvr+20+/Ex9Z5t5ZddKdrZc6dd2DCEyo5G,iv:GNjLBT0S1oiB94SCrH9HRAiqkWPrVH6vkBiGqEG/LV8=,tag:JAT8JW+gCkkyF9fVcY32lQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wejeduv4avzqufj5zec7nepk2vrnzcag9ntj7xlw9zf25unswc0sfhff9j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxODBHcy9UMCtQbTZWNkpQ
            ZkFyMGZJSnMyM2JGVVdwWE8yTll1L0xhajNVClhZQ1lZU1FkQkhENkt5ZFhaY1F5
            UFZnMGFSb2U2TmVzMTN0K0pnRUwyRHcKLS0tIGFOaldHcjBMRjdqWTdLSWRLbHNr
            bU5DWEJPMWVMMWZMbmkyV3V4VnV2bncK8L7yIEIfxp+jWqXRTEi/MhluEh6MB4Dz
            qGj3/YdZP7fwmBZhk+U2KY+E34sNYu+82+HznlYc2qO9ItXWEuAe4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T21:37:52Z"
    mac: ENC[AES256_GCM,data:oqDInKR+vRPcvsOPqIYLpNwVfpsilIvx2DkBMYcyMLuHtQ9rFKpo7RoQ4Zlww+QdWXmntabuzB+YqhSRTZJg6I0vKjomb0/Wiq3qpVAMZQH1AeolSg6btiHk8N3GZIRKh4MKgD7/vyrIL3ld+ozJdbdIBAaow+TmUv0OKWF8CBo=,iv:nYyifqO+Sm9jnJ4QzgTQRbiDHDqDQ3/I5Ye2MtKVfao=,tag:Q25Aan/CKh6f5lDmLllQ3w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
