apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BOCXRwv0HcL4kQI/AKv7m7vgBnueE7hDNwHqp7j8moZPd7Plo3XGQB2Cc9bpRDRh9pTYnQNFWD1Ykee0Fb6wP1N2D9PaZrAC9t/21pErAGBH6/B8za88zzLXEl8xIxaWHe5Ene1u8PJFyVGOh9BPR59JQD1szOSg6cPbVJ9n3rGMac8YgSba9JUrcwWZh3oRh9Rm/MWtUY7ihBiGaU4zy+mb+7aofEKzJ0FcsfpjSFS5NTzjzxkqeTkujb4J0Lu6/QWTacYQX8wjFx0NSQz19ZgaZdTADA8KvYEZo5Y5b8zsdMgRUEaePqyFqDjzZgEv7cXUtkeVWqBEUMyZ5HoJFvrK5PC4175j43US9h74OFy3dhOmTpzJzYUDorrkOb2D,iv:aYv56r2RvD58S6P6BHY0zJWcWKZ94LULAhflAxN0svU=,tag:UUVOJhv8ITQZSM0gRjeSlQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:0wgXxwzc0QgMVmZIY1lyLRaZUgzRLxsQji0TN097HZ3Rk20HKJrSww0GDL5TbWDgFPjKrP/uniHIA0lX4Zw9cX1JJk/HR+kqWOJqapOF/NUektTneUv1GqaiQ7Epk/Q65Y6fmj1l85TflzGDQkmX9xSSyQLtE9SdvAD7BuE8x4LYxkZ7lOjekhJLR3xrDQ2Voj6ECsd5t9eaDAIWCkYfyqO+CI7QtJsC3harKOSUQC8awuaqsLn6LPYj4rzC7VGKqMLli2/Cjo7MQ8oR3Q==,iv:nBAPfaywHnfnnJgS7VSQqt4wM1QgrkmkOzAusffFZiE=,tag:AXa/2vHpw+6fCR71eXQUcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:o+tRuJ1m3YzcQI2y7D1KIVWg9DmYQcouXRORmo3SNEFG8kpUgO13eKUbsxNRfP0eaRKCDm1jDkU9Ctfe2DxI2Fldj996ofQpnOpsUXHlUF8gR+2FbDWi595oP8XJelRZoEaShaAnkuM7/Mq+HYLbGF58+uWOecheNbQneyiWXKE/QjWiq2MrMumCujOuiTbIWH57uLWXxByULIfEK5NdoHzjY1QCjtuK4pWL,iv:5w86NVtw2xhrxdM8DMI0NPNek+XBets61JjTheMbkAs=,tag:EF74rQ+X/SSsjjeRg/CIZA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17yrg4567h6qxz80uvj0h3lxgdk4f0dfmd6kf7xzg5hswtlngsqjqe9fj3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6STBhcHo3ZUdpSmVzNk0v
            K2xFYmFaNDBRKzlJdm44TTdVU0UxU25iNzJFCktiVk1oZXRDcnFmQjZ1RkNCZmtM
            Q1l3OTEzNFZaRGRuWjk0d1pyUGl1elkKLS0tIFN2MzExbnRjWVlUcUxNRkwxT3dh
            K0ZtaUFHaFFLUzJZTm9zejdVdFp5RE0KdxH327cvhz4Z+meqIhZ5NUFFPJihV2rh
            o128QZb0fD6CdIsBRxa4ENuy/Yvo8YHCI/EqQ478qQSjX+Nb39dUxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T04:55:25Z"
    mac: ENC[AES256_GCM,data:z+EtxCNLu/+yCy/ZRx5qrAQHjJYvWtxgQfZdK6zBqS5JU69ESacs2p05fPhjASureDLlX5fk4MPGt6vJBYZ+CXa1SkN1x3N6jwsXacJY4wH9CnC6tB/AVdCKkkrozk4GTV/rrBh0GPWhgEtaQaiea9f9oKY9FhrUCGo/JOvvQF4=,iv:iwJi00Ra8NUNDtgISa66Q6VtR7Z+YFo4W1N5+wYkfJ4=,tag:qlcoLYmu0PyqTaX6qtO4Aw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
