apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: uptime-kuma
    namespace: uptime-kuma
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: uptime-kuma
            version: 12.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-sql"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: uptime.kuma.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      metrics:
        main:
          enabled: false
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 40 1 * * *
