---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: es-sonarr
  namespace: es-sonarr
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultCertificate: domain-0-wildcard
    service:
      main:
        type: ExternalIP
        externalIP: "${SCALE_EMBY_IP}"
        useSlice: false
        ports:
          main:
            protocol: http
            port: 9089
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod 
        hosts:
          - host: sonarr2.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
