---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
  namespace: readarr
spec:
  interval: 15m
  chart:
    spec:
      chart: readarr
      version: 24.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    securityContext:
      readOnlyRootFilesystem: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                READARR__SERVER__PORT: "{{ .Values.service.main.ports.main.port }}"
                READARR__AUTH__METHOD: External
                READARR__AUTH__REQUIRED: DisabledForLocalAddresses
                READARR__APP__THEME: dark
    defaultCertificate: domain-0-wildcard
    service:
      main:
        type: ClusterIP
        ports:
          main:
            port: 8787
    ingress:
      main:
        enabled: true
        integrations:
          homepage:
            enabled: false
            group: "Media Manager"
            widget:
              custom:
                key: "${READARR_KEY}"
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: readarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
              cacheCapacity: 10Gi
#              cleanupTempPVC: true
#              cleanupCachePVC: true
            src:
              enabled: true
              cacheCapacity: 10Gi
#              cleanupTempPVC: true
#              cleanupCachePVC: true
      media:
        enabled: true
        type: nfs
        server: ${SCALE_IP}
        path: ${MEDIA_NFS}
        mountPath: "${MEDIA_LOCAL}"
#      downloads:
#        enabled: true
#        type: nfs
#        server: ${SCALE_IP}
#        path: ${DOWNLOADS_NVME}
#        mountPath: "${DOWNLOADS_NVME_LOCAL}"
