---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
  namespace: rustdesk
spec:
  interval: 15m
  chart:
    spec:
      chart: rustdesk
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: ${CF_S3_RESTIC_URL}
        bucket: ${CF_S3_RESTIC_BUCKET}
        accessKey: ${CF_S3_RESTIC_ID}
        secretKey: ${CF_S3_RESTIC_KEY}
        encrKey: ${CF_S3_RESTIC_KEY}
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    defaultCertificate: domain-0-wildcard
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${RUSTDESK_IP}
        ports:
          main:
            port: 21117
            protocol: tcp
          client1:
            enabled: true
            port: 21118
            protocol: tcp
          client2:
            enabled: true
            port: 21119
            protocol: tcp
          id:
            enabled: true
            port: 21116
            protocol: udp
          id2:
            enabled: true
            port: 21116
            protocol: tcp
          nat:
            enabled: true
            port: 21115
            protocol: tcp
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PORT: "{{ .Values.service.main.ports.main.port }}"
                RELAY: "localhost:{{ .Values.service.main.ports.main.port }}"
                ENCRYPTED_ONLY: 0
                # ALWAYS_USE_RELAY: "Y"
                KEY_PRIV: "${RUSTDESK_KEY_PRIV}"
                KEY_PUB: "${RUSTDESK_KEY_PUB}"
                DB_URL: "{{.Values.persistence.data.mountPath }}/db.sqlite3"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: rustdesk.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
              cacheCapacity: 10Gi
              cleanupTempPVC: true
              cleanupCachePVC: true
            src:
              enabled: true
              cacheCapacity: 10Gi
              cleanupTempPVC: true
              cleanupCachePVC: true
