apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flaresolverr/ks.yaml
  - theme-park/ks.yaml
  - sonarr/ks.yaml
  - pasta/ks.yaml
  - plex/ks.yaml
  - plex-auto-languages/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sabnzbd/ks.yaml
  - tautulli/ks.yaml
  - fileflows/ks.yaml
  - overseerr/ks.yaml
  - rustdesk/ks.yaml
  - kometa/ks.yaml
  - lidarr/ks.yaml
